### ISSUE TITLE
没有看到自然语言搜索的位置和配置, 另外有导入功能吗?

### ISSUE THREAD

**Issue by LiangWei88** [blinko-space/blinko#104]
看截图好像是在右下角, 但是没有看到, 另外 issues 中有人提到导入 memos 但是没有看到导入位置.
是我的版本不对吗? 我使用国内华为云加速镜像, 不知道是不是旧版, 不过也没查到哪里查询 latest 镜像版本的地方

**Comment by LiangWei88** [comment]
![image](https://github.com/user-attachments/assets/966237be-f5bb-4fc2-aec3-10a49736cbfb)

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/95d6da5d-3f36-46e6-b7ec-311f5275dbef)
设置页面有

**Comment by LiangWei88** [comment]
十分感谢, 的确是有的, 不过部署在国内服务器, 访问不了 open api
现在想到两个解决方案, 

一个是链接国内的接口, 不知道是不是可以自定义

另外一种, 是自己部署一个 one api 的接口代理, 不过目前本地测试没有用, 
不知道是不是 http://localhost:3000 这样的地址没有 https 没法用呢?

这个工具非常有用, 十分感谢

**Comment by LiangWei88** [comment]
> ![image](https://private-user-images.githubusercontent.com/186030902/386491055-95d6da5d-3f36-46e6-b7ec-311f5275dbef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODQ1NTAsIm5iZiI6MTczMTY4NDI1MCwicGF0aCI6Ii8xODYwMzA5MDIvMzg2NDkxMDU1LTk1ZDZkYTVkLTNmMzYtNDZlNi1iN2VjLTMxMWY1Mjc1ZGJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxNTI0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWQ5MjlkOTlhZTdlYzEyYmM4NDNlOTk1YmQ5MDVkN2I3NGQxYWQ3MGNjMzQ3OTVhNDc2ZTE1MTA3NDQ5YTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vP70ZOvgLMQbza7ffUVrSaScjQ9Z6uJ5SajK-KuwIg4) 设置页面有

十分感谢, 的确是有的, 不过部署在国内服务器, 访问不了 open api
现在想到两个解决方案,

一个是链接国内的接口, 不知道是不是可以自定义

另外一种, 是自己部署一个 one api 的接口代理, 不过目前本地测试没有用,
不知道是不是 http://localhost:3000/ 这样的地址没有 https 没法用呢?

这个工具非常有用, 十分感谢
