### ISSUE TITLE
单独分享的页面卡片的建议

### ISSUE THREAD

**Issue by HibobacX** [blinko-space/blinko#105]
大佬，建议一下：

单独分享页面优化：

当鼠标悬停在分享内容的卡片上时，摇晃效果过于明显，影响内容阅读。能否减弱这个效果？
如果篇幅大一点的话，在使用鼠标滚轮时，鼠标轻微晃动，卡片也会跟着晃动看着会有点晕。建议在滚动时减小或取消卡片的晃动。
卡片大小和布局：

在PC端，卡片是否可以放大一些？当前只有一个居中的小卡片显得单调。增大卡片大小或增加多个卡片可能会提高视觉效果？
![image](https://github.com/user-attachments/assets/61efbc1f-022c-4adb-a33a-4c44d44b46f9)

**Comment by HibobacX** [comment]
辛苦大佬了

**Comment by blinko-space** [comment]
已经修复
