### ISSUE TITLE
数据排序问题

### ISSUE THREAD

**Issue by leslieyin** [blinko-space/blinko#106]
闪念和笔记的内容均已以数据创建时间降序排列，闪念和笔记的内容转换后排序变以转换时间去排序了，有些时间错乱。看下是否可调整

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blinko-space** [comment]
后面会增加一个设置，按照更新时间或者创建时间排序
