### ISSUE TITLE
“笔记”和“闪念”

### ISSUE THREAD

**Issue by Jimumeor** [blinko-space/blinko#107]
现在的“笔记”和“闪念”定位感觉有点重叠哎，除了“闪念”多一个自动归档的功能，有点小建议大佬看下可行性。
之前用memos也是觉得没有长笔记的地方，只适合写点“灵感”，没有写长笔记的地方，所以是memos和siyuan一起用的，然后siyuan里面有插件可以同步memos的短笔记过去。
所以我想的是，“笔记”是不是可以做的和“闪念”差别大一点，兼顾短笔记和长笔记需求~
长笔记卡片页面
![image](https://github.com/user-attachments/assets/66aadc82-5979-47e7-af1c-5e19d9264e7c)
长笔记正文页面
![image](https://github.com/user-attachments/assets/6039f221-bb99-4545-9c6e-751f27b41e49)
最后，感谢大佬的Blinko，很好用很好看~

**Comment by blinko-space** [comment]
大概的意思是 有不同的视图？例如长篇笔记应该显示1列吗？

**Comment by Jimumeor** [comment]
就是长篇笔记以卡片的形式，展示“标题、前xx字摘要、有图的展示一张封面图、等等”，然后点进去是完整版面都是长笔记内容，可以浏览，编辑
现在的笔记，遇到长笔记和闪念一样，只是多一个“展开”，感觉还是更适合短笔记

**Comment by blinko-space** [comment]
感觉也可以考虑

**Comment by blinko-space** [comment]
https://github.com/blinko-space/blinko/pull/185 
Added blog view for long text
