### ISSUE TITLE
对于其他 ai 接口的对接可能, 必须 https 的接口地址吗

### ISSUE THREAD

**Issue by LiangWei88** [blinko-space/blinko#114]
> ![image](https://private-user-images.githubusercontent.com/186030902/386491055-95d6da5d-3f36-46e6-b7ec-311f5275dbef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODQ1NTAsIm5iZiI6MTczMTY4NDI1MCwicGF0aCI6Ii8xODYwMzA5MDIvMzg2NDkxMDU1LTk1ZDZkYTVkLTNmMzYtNDZlNi1iN2VjLTMxMWY1Mjc1ZGJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxNTI0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWQ5MjlkOTlhZTdlYzEyYmM4NDNlOTk1YmQ5MDVkN2I3NGQxYWQ3MGNjMzQ3OTVhNDc2ZTE1MTA3NDQ5YTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vP70ZOvgLMQbza7ffUVrSaScjQ9Z6uJ5SajK-KuwIg4) 设置页面有

十分感谢, 的确是有的, 不过部署在国内服务器, 访问不了 open api
现在想到两个解决方案,

一个是链接国内的接口, 不知道是不是可以自定义

另外一种, 是自己部署一个 one api 的接口代理, 不过目前本地测试没有用,
不知道是不是 http://localhost:3000/ 这样的地址没有 https 没法用呢?

这个工具非常有用, 十分感谢

_Originally posted by @LiangWei88 in https://github.com/blinko-space/blinko/issues/104#issuecomment-2479188231_

**Comment by blinko-space** [comment]
可以上某宝买中转key很便宜 自己部署的没有试过 理论上是可以请求的 但是docker内部访问的host ip需要做一些转发

**Comment by LiangWei88** [comment]
已经解决, 使用 one-api 就行, 自己本地不知道为什么处理不了, 但是部署到服务器, 暴露公网ip, 是可用的

**Comment by LiangWei88** [comment]
已经解决, 使用 one-api 就行, 自己本地不知道为什么处理不了, 但是部署到服务器, 暴露公网ip, 是可用的
