### ISSUE TITLE
上传文件后无法设置上传文件的位置，例如图片

### ISSUE THREAD

**Issue by Tedcrs** [blinko-space/blinko#142]
我写了一段话，要插入一张图片，我选择上传图片文件，图片只能在卡片最下面显示，我还想在图片下面接着写一段话，发现无法实现这样功能，这种体验是不行的，还望可以改进，还有希望加入obsidian的双链功能，光标悬停在被链接文件时，可以弹出一个预览窗口，这种体验不是搜索可以替代，还可以加强卡片之间的联系，还有请求安卓APP客户端早日上线，祝越来越好，加油。

**Comment by blinko-space** [comment]
1.目前所有附件（包含图片）都是展示在下方，如果要在文本中加入图片，可以使用markdown的插入图片。
2.目前不打算加入双链，因为加入了RAG检索
3.安卓app暂时也未有开发的打算

**Comment by Tedcrs** [comment]
麻烦可以考虑上一下安卓APP端




挂着的耗子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blinko-space/blinko"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月20日(星期三) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blinko-space/blinko] 上传文件后无法设置上传文件的位置，例如图片 (Issue #142)





 
1.目前所有附件（包含图片）都是展示在下方，如果要在文本中加入图片，可以使用markdown的插入图片。
 2.目前不打算加入双链，因为加入了RAG检索
 3.安卓app暂时也未有开发的打算
