### ISSUE TITLE
录音和拍照功能无法使用

### ISSUE THREAD

**Issue by smallxi** [blinko-space/blinko#164]
录音和拍照功能无法使用。拍照获取不到画面，录音点击后没有反应，请问这是什么原因导致的呢

**Comment by Jonnyan404** [comment]
给浏览器授权

**Comment by blinko-space** [comment]
录音和拍照由于浏览器的限制 需要使用https

**Comment by ljcz-fujia** [comment]
@blinko-space 我这最新版本工具栏没有语音和拍照选项，浏览器和安卓都没有，是没开https就不会显示吗

---
@blinko-space My latest version of the toolbar does not have voice or photo options, and there is no browser or Android. If you don't turn on https, will it not be displayed
