### ISSUE TITLE
导入的笔记中会出现标签样式不生效

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#167]
**Describe the bug**
从memos导入笔记后,会出现一些标签样式不生效,主要出现在当行内有其他文字内容或者标签后没有换行时.不生效的样式依然会出现在标签索引中.当在不生效后的标签后面换行后即可恢复,并且删除换行后也能保持标签样式

**To Reproduce**
1. 导入memos笔记内容
2. 发现某些标签样式不生效

**Expected behavior**
所有的笔记内容的标签样式应该能正常生效

**Screenshots**
![image](https://github.com/user-attachments/assets/af23af95-d731-461c-9fa1-a3bb49f6e9fa)

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - v0.8.8

**Comment by blinko-space** [comment]
这个标签之间是否没有空格？

**Comment by blinko-space** [comment]
可以提供这张卡片原始的markdown吗

**Comment by BryceWG** [comment]
原始markdown:
#个人 #思想 
金钱是社会的信用符号，
具有调用别人时间的能力。

这个笔记是我从memos中导入的,但手动复制进blinko能正常显示.
我已经把出错的卡片都改过来了，可以确认两个标签之间包含了空格,因为我是通过在出问题的标签后面加入一个换行解决的,加空格也没用

**Comment by blinko-space** [comment]
这是ui的bug 现在已经修复
