### ISSUE TITLE
手机端底部按钮过多

### ISSUE THREAD

**Issue by smallxi** [blinko-space/blinko#171]
需求一：
手机端底部按钮过多，手机有些功能（例如插入网络图片，代码块，拍摄照片）是不常用的，希望可以折叠或者隐藏。

需求二：
搜索功能能不能加个时间选择，可以回顾一段时间内的笔记

**Comment by smallxi** [comment]
![Uploading Screenshot_20241124_123600_mark_via_Shell_edit_696990228879697.jpg…]()

**Comment by blinko-space** [comment]
1已经修复 不同issue尽量分开提交 2移到https://github.com/blinko-space/blinko/issues/173
