### ISSUE TITLE
增加笔记向量嵌入范围筛选

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#172]
**Is your feature request related to a problem? Please describe.**
增加笔记向量嵌入范围筛选,能够指定哪些或哪些不进行向量嵌入,在使用第三方API服务时保护隐私不泄露

**Describe the solution you'd like**
很多人没有能力在本地运行向量嵌入模型,通常会使用第三方API服务对笔记进行嵌入,可按标签范围进行筛选,防止重要隐私内容泄露

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/fd1ede46-a2ba-4117-baec-b932c3b8f70d)
