### ISSUE TITLE
Previewing videos or audio

### ISSUE THREAD

**Issue by zarevskaya** [blinko-space/blinko#18]
Hello, 
Thank you for sharing your work! 

Have you planned to make it possible to preview a video or listen to an audio file (like a audio note) directly in the application?

Have a nice day!

**Comment by blinko-space** [comment]
Hi, already got your request, I'm working on adding this feature in the next version

**Comment by zarevskaya** [comment]
Amazing! Thanks!

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/420457f4-cde0-4f8a-ba6f-8d1863628ecc)
This feature is supported in v0.0.21

**Comment by zarevskaya** [comment]
Great! I try soon 🤤

**Comment by zarevskaya** [comment]
Good job!
![Screenshot_20241107_192935](https://github.com/user-attachments/assets/70631933-eeaa-4785-8571-ffd08c56e29a)
