### ISSUE TITLE
stuck in hashtag selection

### ISSUE THREAD

**Issue by swinxx** [blinko-space/blinko#181]
there is still a small bug, when selecting a hashtag, the selection menu suddenly appears top left corner a second time. 

here is the video: 

https://github.com/user-attachments/assets/6c2526fb-c288-445e-ab39-97bedcbbfd34

**Comment by swinxx** [comment]
it is not possible to create a new hashtag, cause the process is messed up. it would be a godsend if you find and solve this bug

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)
