### ISSUE TITLE
文章浏览视图的数字序号显示异常

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#188]
**Describe the bug**
文章浏览视图的数字序号显示异常,只显示了一半内容

**Screenshots**
![image](https://github.com/user-attachments/assets/9626e916-f818-41e3-89d1-3c2d7e3883fe)
如序号1. 2. 3.

**Desktop (please complete the following information):**
 - Windows 11
 - chrome
 - v0.9.6

**Comment by blinko-space** [comment]
我也是windows好像没有复现
![image](https://github.com/user-attachments/assets/b70e569e-372a-4ee7-8f3f-15a2f070a556)

**Comment by BryceWG** [comment]
我的chrome和firefox内核都这样,安卓又是正常的,可能是字体问题吗?因为我电脑换过字体

**Comment by blinko-space** [comment]
应该是 因为这里没做特殊处理
