### ISSUE TITLE
卡片编辑器中的编号列表符号显示异常

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#189]
**Describe the bug**
卡片编辑器中的编号列表符号显示异常,编号列表和(无序)列表的符号是一样的点号,应该和文章显示一致为1. 2. 3.

**Screenshots**
卡片编辑器视图:
![nqgiws1m wqs](https://github.com/user-attachments/assets/22767d06-4a76-42ed-9eca-b64d739948f5)
文章视图(还有数字序号显示一半的bug):
![0gnh4cwc bxs](https://github.com/user-attachments/assets/fa33440c-5cc3-47f0-bc8b-fe40abca34e1)

**Desktop (please complete the following information):**
 - Windows11
 - chrome
 - v0.9.6

**Comment by blinko-space** [comment]
可以提供一下原始的markdown吗

**Comment by BryceWG** [comment]
煤气灯效应的起源、定义及应对
#Personal/自我补足/内在认知/心理学
起源与历史背景
源于1938年舞台剧《煤气灯》及1944年电影改编，描述通过操控环境使人怀疑自身感知的情节。
心理学界在概念提出后开始关注情感操控与心理虐待。
定义与特征
一种心理操纵，操纵者让受害者质疑自己的记忆和理智以达到控制目的。
受害者逐渐失去自信，依赖操纵者。
应对策略
保持对自身记忆和感知的信任。
寻求外界支持，与可信赖的朋友或专业人士交流。
识别操控行为，了解其特征并及时反抗。
现实案例与解决
案例中，小李通过外界支持和专业帮助识别并摆脱了煤气灯效应。
未来发展与技术支持
提高公众认知，开发干预和治疗方法如认知行为疗法（CBT）。
利用心理健康支持系统提供早期预警和干预。

**Comment by BryceWG** [comment]
### 煤气灯效应的起源、定义及应对

#Personal/自我补足/内在认知/心理学 

1. 起源与历史背景

* 源于1938年舞台剧《煤气灯》及1944年电影改编，描述通过操控环境使人怀疑自身感知的情节。
* 心理学界在概念提出后开始关注情感操控与心理虐待。

1. 定义与特征

* 一种心理操纵，操纵者让受害者质疑自己的记忆和理智以达到控制目的。
* 受害者逐渐失去自信，依赖操纵者。

1. 应对策略

* 保持对自身记忆和感知的信任。
* 寻求外界支持，与可信赖的朋友或专业人士交流。
* 识别操控行为，了解其特征并及时反抗。

1. 现实案例与解决

* 案例中，小李通过外界支持和专业帮助识别并摆脱了煤气灯效应。

1. 未来发展与技术支持

* 提高公众认知，开发干预和治疗方法如认知行为疗法（CBT）。
* 利用心理健康支持系统提供早期预警和干预。
