### ISSUE TITLE
希望可以在设置里增加停用用户注册的功能。

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#19]
希望可以在设置里增加停用用户注册的功能。

私人使用的话，暴漏在外网还是希望可以增加停用注册功能的开关哈。

感谢大佬！

**Comment by blinko-space** [comment]
目前是只能有一个账户的 后端做了限制 注册过管理员账户之后就不能在注册了

**Comment by i-iooi-i** [comment]
> 目前是只能有一个账户的 后端做了限制 注册过管理员账户之后就不能在注册了

嗯嗯 好嘞  这就阔以放心用啦，谢谢大佬。
