### ISSUE TITLE
Add 2FA or MFA for better security

### ISSUE THREAD

**Issue by MFYDev** [blinko-space/blinko#190]
It's a quick note app, 2fa or mfa should be added for better security and privacy reasons.
@blinko-space

**Comment by blinko-space** [comment]
Yes this will be considered for inclusion in subsequent releases

**Comment by WyInnovate** [comment]
期待以后增加2FA

**Comment by no8ody** [comment]
I would also very much welcome it if 2FA and/or #211

**Comment by ArthurK0** [comment]
I hope that FIDO2 will also appear, perhaps

**Comment by blinko-space** [comment]
v0.22.0 now support https://github.com/blinko-space/blinko/commit/317dabbca053fec4504f575e248632d6f037774d
