### ISSUE TITLE
代码块中的# 被自动当成Tag处理，导致Tag分类紊乱。

### ISSUE THREAD

**Issue by quou2006** [blinko-space/blinko#192]
代码块中的# （代码注释）被自动当成Tag处理，导致Tag分类紊乱。希望能够单独处理代码块。

**Comment by blinko-space** [comment]
我这边似乎无法复现该问题，可以提供markdown吗

**Comment by quou2006** [comment]
test

#这是第一行代码注释111
1111111
#这是第二行代码注释222
2222222
------------------------------我刚开始使用blinko，还不清楚如何提供markdown格式。我简要说说复现流程：第一行我输入test，回车换行，然后点击’插入代码块‘图标，直接粘贴接下来的4行测试文字代码，发布。然后左侧tag列表就会出现#行对应的文本tag。
![image](https://github.com/user-attachments/assets/3ef0c358-51d2-45ff-8538-56f0fd9e758b)

**Comment by Jonnyan404** [comment]
能够复现。我这里也一样
另外补充一点，如果代码块里只有注释，会直接消失

```
#这是测试
```
