### ISSUE TITLE
不同嵌入模型的嵌入纬度可能导致无法进行对话

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#193]
**Describe the bug**
不同嵌入模型嵌入纬度不同导致无法进行对话。openai的text-embedding-3-large的嵌入纬度为3072，text-embedding-3-small和ada-002都是1536，使用large进行嵌入后进行对话就会出现报错

**To Reproduce**
1. 使用openai的text-embedding-3-large进行强制重建
2. 使用ai对话
3. 发送消息出现报错

**Expected behavior**
ai查找应该可以适应不同纬度的向量信息，除了text-embedding家族的1536和3072维，还有其他的一些嵌入模型可能是1024，768，4096等纬度

**Screenshots**
![1000025775](https://github.com/user-attachments/assets/b42ba0f2-5d62-457c-bc06-77d628e289ca)

**Smartphone (please complete the following information):**
 - Device: 魅族21
 - OS: flyme11/Android14
 - Browser via
 - Version v0.10.2

**Comment by BryceWG** [comment]
哪里的BAAI?硅基家的embedding都是1024维

**Comment by StrayDogA8** [comment]
就是硅基的BAAI/bge-m3。你可以试试，text-embedding-3-large是兼容1024维的。

**Comment by BryceWG** [comment]
啊?我试过了bge-m3,我后来又换到large也不行,但是我之前用ada002是可以的

**Comment by BryceWG** [comment]
我就是这样的,嵌入过程都没什么问题,但对话会报错.
主要是我测试的text-embedding-3-small和ada002都可以进行问答,然后查了发现这两个都是1536维,其他维度的就不行,也都是强制重建

**Comment by blinko-space** [comment]
这个问题在0.11.0已经修复 是强制重建的问题
