### ISSUE TITLE
Indentation of code pasting

### ISSUE THREAD

**Issue by Fabeuss** [blinko-space/blinko#196]
**Describe the bug**
Indentation issue for code

**To Reproduce**
1. Paste some code (YML, CSS)
2. Check indentation
3. Formatting issue...It looks like Blinko is incorrectly reformatting the code when pasting.

**Expected behavior**
When pasting code into yml, for example, there must be a 2-column indentation.

**Screenshots**
![Screenshot 2024-11-28 at 10-11-31 Blinko](https://github.com/user-attachments/assets/cedd0e99-71d1-4540-b816-e17ddcec4fd0)

**Desktop (please complete the following information):**
 - OS: Windows, Linux...
 - Browser: Firefox

**Additional context**
When I paste code into Hoarder, for example, the code remains correctly formatted...

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)
