### ISSUE TITLE
闪念笔记编辑保存后会跳转到全部笔记视图

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#199]
**Describe the bug**
对已保存的闪念笔记编辑保存后，网页会跳转到全部笔记视图，而不是留在闪念视图

**Expected behavior**
笔记编辑后停留在原本视图界面

**Smartphone (please complete the following information):**
 - Device: 魅族21
 - OS: flyme11/Android14
 - Browser via
 - Version v0.11.2

**Comment by blinko-space** [comment]
我这边没有复现你说的问题

**Comment by BryceWG** [comment]
确实,我也没有再复现了,但是我全是遇到过两次进入全部笔记的页面,可能复现步骤不对
