### ISSUE TITLE
Loading setting

### ISSUE THREAD

**Issue by eallion** [blinko-space/blinko#20]
When logging in on other devices, settings cannot be loaded correctly and need to be re-set once.

**Comment by eallion** [comment]
It may be due to the deployment to the CDN, but the fact that it cannot be deployed to the CDN is also a bug.

Just tested on Aliyun ESA, origin host is http://IP:1111, no cache.

**Comment by blinko-space** [comment]
> When logging in on other devices, settings cannot be loaded correctly and need to be re-set once.

The settings are stored in the database, can you describe in detail which one is not loaded correctly?

**Comment by eallion** [comment]
- Login -> set Preference & AI -> Logout -> reLogin -> lost Preference & AI config
- Post Blinko or Note, logout, restart docker container, relogin, lost all Blinko and Notes

Tested on: 0.0.23, 0.0.24, postgres:14, postgres:14-alpine, postgres:15-alpine, no CDN

**Comment by blinko-space** [comment]
The problem you describe seems to be a database problem, if the database stores this data it is not lost when logging in again, have you tried going into the database to check?

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/1e3a1f47-8e80-42c9-9e0e-173486f0994a)

You can check the 'config' table, try restarting the database, see if you lose any data.

**Comment by eallion** [comment]
```
postgres=# SELECT * FROM config;
 id | key | config 
----+-----+--------
(0 rows)
```
Lost all data and reset to default after docker restarted.
```
    volumes:
      - ~/your-name/.blinko:/app/.blinko 
```
Uncommented volumes.

**Comment by blinko-space** [comment]
The mounting of volumns does not affect database connections.I suggest you connect to an external database to confirm that the problem is a database issue
```js
docker run -d \
  --name blinko-website \
  --network blinko-network \
  -p 1111:1111 \
  -e NODE_ENV=production \
  -e NEXTAUTH_SECRET=my_ultra_secure_nextauth_secret \
  -e DATABASE_URL=postgresql://postgres:mysecretpassword@your-external-database:5432/postgres \
  --restart always \
  blinkospace/blinko:latest
```

**Comment by eallion** [comment]
The solution is the persistence of PostgreSQL.

https://github.com/blinko-space/blinko/blob/main/docker-compose.prod.yml

```diff
postgres:
    ...
+   volumes:
+     - ~/your-name/db:/var/lib/postgresql/data
```
