### ISSUE TITLE
增加召回笔记数量选项

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#202]
**Is your feature request related to a problem? Please describe.**
希望可以增加一个选择召回笔记数量的选项,或者设置一个笔记相似度阈值筛选.现在只能返回两个笔记内容,有些场景是不够的
![ub2auiwc row](https://github.com/user-attachments/assets/a38f2d93-5ef2-453c-93e1-cd500951b8dc)

**Describe the solution you'd like**
增加召回笔记数量的选项,可以选择一次搜索召回前多少个最相关的笔记.或者增加有一个相似度阈值,笔记向量相似度高于一定数值就全部召回.
例如dify的知识库设置:
![icxvnuv0 l0y](https://github.com/user-attachments/assets/d9201bce-569e-4590-a7e2-e68c304d2a40)
topk是召回片段数量,score阈值是用来过滤相似度的设置.两者可以共存,也可以只增加一个"topk"

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/2ce9ac23-7bb9-4817-a9e0-110aaab62921)
增加了topk 相似度 和查询结果多样性权重
