### ISSUE TITLE
建议减少动画，增加流畅度

### ISSUE THREAD

**Issue by smallxi** [blinko-space/blinko#207]
相比memos我非常喜欢这个系统的功能，接入ai非常强大！
感谢作者！
就是如果能把流畅度优化下就更好了，日常用下来总觉得不流畅，卡卡的

**Comment by blinko-space** [comment]
卡卡的具体是指哪里卡呢 可以详细描述一下吗

**Comment by BryceWG** [comment]
动画还好吧?卡顿延迟可能是页面切换后网页加载需要时间?

**Comment by smallxi** [comment]
有可能是加载需要时间。
该程序功能强大很喜欢，但是没有memos轻快，舒服的感觉
我说下我自己的想法，用手机端较多，都针对于手机端：
1、选择标签查看相对应的笔记时是否可以使用类似ajax方式请求
2、标签选择容易误触emoji图标更换，建议换到3点…里进行图标更换
3、笔记文章点击后能否不要动画直接新开页面
4 、笔记中的标签点击能否不执行任何操作，不跳转all?searchTex＝

**Comment by blinko-space** [comment]
加载感觉到卡顿可能是上边的进度条加了两百毫秒的延迟消失 现在去掉了
1.这个只是做了一层路由跳转 数据也是客户端请求的
2.已经修改
3.这个考虑到如果有很多笔记 打开之后返回不好定位到当前笔记 必须要在单页中使用
4.这是用户提的一个需求方便快速筛选标签
