### ISSUE TITLE
请问笔记的排序逻辑是怎样的呢？

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#21]
![image](https://github.com/user-attachments/assets/ccdf7e5d-b00f-407c-b23d-5ae3525bc9f8)

比如记录了一条笔记，但是这条笔记排序是没有按照时间线的顺序排在最顶端的。
这种排序看上去是随机。
那么问题是，假设有几百条笔记，笔记却是随机排序的话，那么这条最新的笔记会在发送之后，就会消失在茫茫笔记中不知道排到哪里去了。😂

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/a35423dc-5820-47f1-bc35-0ac0e0909446)

当使用暗色主题的时候，卡片笔记的字体颜色会变得很浅了。

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/dfc20f91-52cc-4d8d-a16f-e70f8d329c8b)

另外就是在笔记页面，随机测试记录了40多条笔记，但是实际显示的只有十条笔记。
即便刷新页面也无法loaded这些笔记了。
通过TAGS是能筛选到这些笔记的，只是不显示而已。
希望大佬可以添加自动载入笔记的功能，或者手动点击触发载入笔记的功能。

**Comment by blinko-space** [comment]
> ![image](https://private-user-images.githubusercontent.com/1827701/384443923-ccdf7e5d-b00f-407c-b23d-5ae3525bc9f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTg1OTEsIm5iZiI6MTczMTExODI5MSwicGF0aCI6Ii8xODI3NzAxLzM4NDQ0MzkyMy1jY2RmN2U1ZC1iMDBmLTQwN2MtYjIzZC01YWUzNTI1YmM5ZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDIxMTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlNGI5OWE4MTkxNWY5ZDI0Zjg1YTA0ZmY3ZDY0ZDc5N2NkYjdjODVhZjRmNzE3YTQ3NTRiMmVmOGNhMWRjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lAj-LQQLQMi2v7E-nKxWm5oRvG-_5cA9hZAGQfxEoJI)
> 
> 比如记录了一条笔记，但是这条笔记排序是没有按照时间线的顺序排在最顶端的。 这种排序看上去是随机。 那么问题是，假设有几百条笔记，笔记却是随机排序的话，那么这条最新的笔记会在发送之后，就会消失在茫茫笔记中不知道排到哪里去了。😂

笔记是按照置顶，更新时间来排序的 ，更新完了一篇笔记会自动在最前方

**Comment by blinko-space** [comment]
fixed on v0.0.25

**Comment by blinko-space** [comment]
fixed on v0.0.25

**Comment by i-iooi-i** [comment]
> > ![image](https://private-user-images.githubusercontent.com/1827701/384443923-ccdf7e5d-b00f-407c-b23d-5ae3525bc9f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTg1OTEsIm5iZiI6MTczMTExODI5MSwicGF0aCI6Ii8xODI3NzAxLzM4NDQ0MzkyMy1jY2RmN2U1ZC1iMDBmLTQwN2MtYjIzZC01YWUzNTI1YmM5ZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDIxMTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlNGI5OWE4MTkxNWY5ZDI0Zjg1YTA0ZmY3ZDY0ZDc5N2NkYjdjODVhZjRmNzE3YTQ3NTRiMmVmOGNhMWRjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lAj-LQQLQMi2v7E-nKxWm5oRvG-_5cA9hZAGQfxEoJI)
> > 比如记录了一条笔记，但是这条笔记排序是没有按照时间线的顺序排在最顶端的。 这种排序看上去是随机。 那么问题是，假设有几百条笔记，笔记却是随机排序的话，那么这条最新的笔记会在发送之后，就会消失在茫茫笔记中不知道排到哪里去了。😂
> 
> 笔记是按照置顶，更新时间来排序的 ，更新完了一篇笔记会自动在最前方

辛苦大佬。
重新拉取了最新镜像。清空笔记，重新测试了一下，现在的笔记排序是正确的了。
