### ISSUE TITLE
LDAP / Authentication Support for multi-users

### ISSUE THREAD

**Issue by accforgithubtest** [blinko-space/blinko#211]
Thanks for creating this amazing app, just found it and this is just great.

Would you please consider adding support for ldap and authentication to enable multi user setup ?

Would be awesome to see this project work with self hosted solutions like [lldap](https://github.com/lldap/lldap) and [authelia](https://github.com/authelia/authelia), as well as several other such standards based solutions.

**Comment by blinko-space** [comment]
Yes I see a lot of people needing support for SSO which will be supported in a later release

**Comment by blinko-space** [comment]
now support in [v0.32.0](https://github.com/blinko-space/blinko/releases/tag/v0.32.0)
