### ISSUE TITLE
# not possible to add new hashtag.

### ISSUE THREAD

**Issue by swinxx** [blinko-space/blinko#212]
trying to create a new # fails.. 

when using # to create new hashtag, the selection opens up. 
trying to create a new hashtag fails in pasting the selection.

example 
# -> opens up the hashtag selection (existing hashtags e.g. #example)
#xyz  (ENTER) 
leads to ->

#example xyz

**Comment by weado** [comment]
Hi, I have the same issue : 
I currently have 2 hashtags in my blinko. When I try to create one, I start by typing the hashtag and when I press the space bar, it changes the word to an existing hashtag.
Example (I writed new hastag and when I press the space bar, it change it) : 
![image](https://github.com/user-attachments/assets/f211a819-fbbe-4e33-856a-a0852d58cfd7)
![image](https://github.com/user-attachments/assets/3c907c0c-e5c3-47c2-a4b5-9e46493aaa6e)

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)

**Comment by FlashlightPete** [comment]
Hi, I am having this issue in 2026 with no luck troubleshooting. Maybe I'm missing something?
