### ISSUE TITLE
长笔记卡片的标题排除标签 || Title exclusion tag for long note cards

### ISSUE THREAD

**Issue by StrayDogA8** [blinko-space/blinko#215]
目前长笔记在列表页的卡片样式会自动取笔记第一行内容作为标题，但从习惯上第一行往往是标签，而且Blinko自身的AI标签功能也是自动把标签插到第一行，这导致了长笔记卡片会把标签作为标题而不是正文的首行。
建议自动过滤标签内容，把除标签外的首行内容作为标题。

---
Currently, the card style of long notes on the list page will automatically take the first line of the note as the title, but customarily the first line is often a label, and Blinko's own AI label function also automatically inserts the label into the first line, which results in Long note cards will use the label as the title instead of the first line of the text.
It is recommended to automatically filter the tag content and use the first line of content except the tag as the title.

**Comment by blinko-space** [comment]
现在已经支持
