### ISSUE TITLE
使s3文件可以直接从s3服务获取而不经过服务器 || Enables s3 files to be obtained directly from the s3 service without going through the server

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#216]
**Is your feature request related to a problem? Please describe.**
使s3文件可以直接从s3服务获取而不经过服务器,未开启cdn的服务器每次启动blinko时加载文件会很慢

**Describe the solution you'd like**
考虑到有些s3服务存在流量费用压力,这个特性可以设置为可选项

---
**Is your feature request related to a problem? Please describe.**
This allows s3 files to be obtained directly from the s3 service without going through the server. Servers that do not have cdn turned on will be very slow to load files every time they start blinko.

**Describe the solution you'd like**
Considering that some S3 services have traffic cost pressure, this feature can be set as optional.

**Comment by shinyes** [comment]
确实需要这个功能，并且设置为可选择的最好，毕竟有些对象存储在内网流出不计算费用。
