### ISSUE TITLE
ai 对话搜索结果太少, 答非所问, 润色功能添加奇怪符号, 希望可以自定义 prompt || ai There are too few dialogue search results, and the answers are incorrect. The polish function adds strange symbols. I hope the prompt can be customized.

### ISSUE THREAD

**Issue by LiangWei88** [blinko-space/blinko#217]
ai 连接的是千问32b的模型, 嵌入是网易 b3m 模型
使用ai提问搜索的时候, 答非所问, 然后给出的相关记录太少.

另外在输出润色的功能上老是给出一些转义字符, 保存后形成 /Blinko/ 之类的斜杠符号
说不定是模型问题, 希望可以自己自定义 prompt 进行调试

目前最好用的功能是 ai 标签
另外一个就是占用的 内存越来越高了, 数据库 50-70m正常
本体目测基本超过200, 如果能少一些就好了

不过这的确是一个很好的软件. 辛苦大佬了.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---
The ai is connected to the Qianwen 32b model, and the embedded model is the NetEase b3m model.
When using AI to ask questions and search, the answers are incorrect and too few relevant records are given.

In addition, the output polishing function always provides some escape characters, which form slash symbols such as /Blinko/ after saving.
Maybe it's a model problem. I hope I can customize the prompt for debugging.

The best feature currently is the ai tag
The other thing is that the memory occupied is getting higher and higher. The database is 50-70m normal.
The visual inspection of the main body is basically over 200. It would be better if it could be less.

But this is indeed a very good software. Thank you for your hard work.

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expect to happen.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BryceWG** [comment]
设置有topk和score阈值设置,你可以自己改一下

**Comment by LiangWei88** [comment]
> 设置有topk和score阈值设置,你可以自己改一下
> 
> There are topk and score threshold settings, you can change them yourself

感谢回复，经测试的确发挥了作用，现在已经能够顺利搜索到内容了。

我尝试使用了千问 2.5 14b 和 google gemma 27b 模型，在此过程中主要遇到了两个虽有些纠结但能使用的问题：
- 当我仅想找到相关笔记时，它会给出大量其他建议。
- 在扩写的时候，会添加许多 &#x20; 符号。

我对代码进行了克隆并查看，发现这些问题似乎都是在 prompt 层面注入的。我在想，如果能够提供选择使用默认 prompt 或者自定义 prompt 的功能就更好了。另外，想了解一下目前是否有第三方插件的功能或者相关的预期计划呢？这样或许就能够按照自身需求进行改动了。 


![image](https://github.com/user-attachments/assets/f78f3503-996f-4330-9a2c-48583bee2a47)
![image](https://github.com/user-attachments/assets/27d7b9de-1ffd-4baf-be5a-4bcbc6ce7992)
![image](https://github.com/user-attachments/assets/68ffacc5-d5c5-4aae-9967-19fc2f6d1840)
![image](https://github.com/user-attachments/assets/5efedf06-a35b-4b20-bc62-5aacf41a47ce)

**Comment by BryceWG** [comment]
我觉得你可以试试更好的问答模型,embedding模型也可以更换,比如bge-m3

**Comment by blinko-space** [comment]
v17.0.1已经优化ai写作

**Comment by LiangWei88** [comment]
> v17.0.1已经优化ai写作
> 
> v17.0.1 has optimized ai writing

太厉害了, 感谢
