### ISSUE TITLE
增加一个只搜索笔记但不回答的AI功能 || Add an AI function that only searches notes but does not answer

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#224]
**Is your feature request related to a problem? Please describe.**
增加一个只搜索关联度较高的笔记但根据搜索到的笔记内容进行回答的AI功能

**Describe the solution you'd like**
相当于一个更高效的搜索功能,这种情况下不需要考虑笔记数量对ai上下文的影响,也不需要等到ai回答才能看到相关联的笔记,只需要展示和搜索关键词相关的所有笔记(考虑score阈值),也是从flomo获得的灵感
![qiw5ifgo zsq](https://github.com/user-attachments/assets/b166e641-7768-4006-b9cd-c3403771c467)
![grsjofvs 01v](https://github.com/user-attachments/assets/90f059fc-efd1-4fb0-ab88-1c2b37f977c1)
当然也可以对当前的ai对话进行改进,增加切换对话的模式的选项

---
**Is your feature request related to a problem? Please describe.**
Add an AI function that only searches for highly relevant notes but answers based on the content of the searched notes.

**Describe the solution you'd like**
It is equivalent to a more efficient search function. In this case, there is no need to consider the impact of the number of notes on the AI ​​context, and there is no need to wait for the AI ​​to answer before you can see the associated notes. You only need to display all notes related to the search keywords ( Consider score threshold), also inspired by flomo
![qiw5ifgo zsq](https://github.com/user-attachments/assets/b166e641-7768-4006-b9cd-c3403771c467)
![grsjofvs 01v](https://github.com/user-attachments/assets/90f059fc-efd1-4fb0-ab88-1c2b37f977c1)
Of course, the current AI dialogue can also be improved and the option to switch dialogue modes can be added.

**Comment by LiangWei88** [comment]
+1
#217 我遇到的问题也可以这样解决

**Comment by blinko-space** [comment]
那感觉可以在搜索旁边加一个ai搜索或者增强搜索的东西

**Comment by BryceWG** [comment]
可以，我要把笔记的向量数据用到机制哈哈

**Comment by LiangWei88** [comment]
期待更新

**Comment by LiangWei88** [comment]
> https://github.com/blinko-space/blinko/releases/tag/v0.16.0

Thank you
