### ISSUE TITLE
Docker container for Blinko making outbound connection to github

### ISSUE THREAD

**Issue by woreibi** [blinko-space/blinko#225]
Hi,
I noticed that blinko container keep trying to make connections to github after it has been deployed.
What is it trying to fetch or download from github after container is deployed ? I was expecting it NOT to make any connections outbound unless we use AI feature.

Appreciate clarification and feedback.

attached screen shot of traffic that was intercepted by firewall.

Thank you,
![Screenshot 2024-12-01 215602-blinko](https://github.com/user-attachments/assets/bb6480bf-bf10-445e-bdbb-47469d176139)

**Comment by blinko-space** [comment]
yes,blinko will get the lastest version from github api ,you can check the code
https://github.com/blinko-space/blinko/blob/main/src/server/routers/public.ts#L27
