### ISSUE TITLE
播放视频会迅速扩大内存占用 || Playing videos will quickly expand the memory footprint

### ISSUE THREAD

**Issue by shinyes** [blinko-space/blinko#229]
**Describe the bug**
播放视频会迅速扩大内存占用

**To Reproduce**
播放视频，目前尝试过两个 50MB 左右的视频都会导致这样的问题

**Screenshots**
![image](https://github.com/user-attachments/assets/5a9f32c3-5a5f-4cac-9786-8237c0941167)

---
**Describe the bug**
Playing videos will quickly expand memory usage

**To Reproduce**
Playing videos. I have tried two videos of about 50MB each, which will cause this problem.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a9f32c3-5a5f-4cac-9786-8237c0941167)

**Comment by blinko-space** [comment]
fixed https://github.com/blinko-space/blinko/releases/tag/v0.13.2
