### ISSUE TITLE
Support for Gemini

### ISSUE THREAD

**Issue by ExXxtr3me** [blinko-space/blinko#235]
**Is your feature request related to a problem? Please describe.**
Would it be possible to also support Google Gemini and not only OpenAI and Ollama?
In the Hoarder app (https://hoarder.app/) i was able to use Gemini with the following API Endpoint, but that doesn't seem to work with Blinko: https://generativelanguage.googleapis.com/v1beta/

**Comment by BryceWG** [comment]
Currently, gemini official has basically supported the OpenAI format protocol, you can refer to Google's documentation

**Comment by ExXxtr3me** [comment]
> Currently, gemini official has basically supported the OpenAI format protocol, you can refer to Google's documentation

Yes i know, that's how i use it for example in Hoarder, but it's not working in Blinko, maybe i'm doin something wrong but i'm not a pro in this stuff.

**Comment by BryceWG** [comment]
I haven't carefully studied the openai format calls of Gemini either

**Comment by StrayDogA8** [comment]
Try changing the Embedding Model to text-embedding-004
