### ISSUE TITLE
希望添加笔记与闪念的导出功能 || Hope to add the export function of notes and thoughts

### ISSUE THREAD

**Issue by Myra009** [blinko-space/blinko#236]
希望添加笔记与闪念的导出功能，
能导出为md格式最好，这样放在本地的md阅读器，就能看到了。

---
I hope to add the export function of notes and thoughts.
It is best to export it to md format, so that you can see it in a local md reader.

**Comment by i-iooi-i** [comment]
同希望可以导出 md格式 ，这样就可以定期在Obsdian里面同步整理一份笔记到本地了，心理上会比较安心一些。

**Comment by blinko-space** [comment]
最新版本已经支持
