### ISSUE TITLE
增加 webhook 功能, 方便用户自己增加其他功能 || Add webhook function to facilitate users to add other functions themselves

### ISSUE THREAD

**Issue by LiangWei88** [blinko-space/blinko#237]
之前因为 ai 从 memos 转过来用 blinko, 后来发现 ai 搜索和校对功能比较难自定义, 常使用 memos webhooks + n8n 实现了相同的功能, 发现自由度很大. 但是回过头来一看, 你已经更新 0.16, 已经有我想要的 ai 搜索功能, 只能说前端大佬牛逼.

不过在改造过程中, 也发现 memos 的 webhook 系统很好, 可以在没有插件系统的情况下, 实现一定的用户自定义, 如果 blinko 也有就太棒了

目前 memos 的 webhook 在增删改的时候触发, 我的操作通过 Webhook 接收 memo 内容，使用 LLM 校对并生成标签，然后更新原始 memo 内容。后续还想要的功能是接收到 memo 自动存入自己的向量数据, 就可以自定义实现语义化搜索, 还有可以定时对每天的笔记进行汇总, llm 进行总结, 回顾今天的一切, 用起来发现 n8n 真的很多可能性

---
I switched from memos to blinko for ai, but later found that the search and proofreading functions of ai were difficult to customize. I often used memos webhooks + n8n to achieve the same function, and found that the degree of freedom was great. But looking back, you have updated 0.16, already has the AI ​​search function I want, I can only say that the front-end guy is awesome.

However, during the transformation process, I also found that the webhook system of memos is very good. It can achieve certain user customization without a plug-in system. It would be great if blinko also has it.

Currently, the webhook of memos is triggered when adding, deleting or modifying. My operation receives the memo content through the webhook, uses LLM to proofread and generate tags, and then updates the original memo content. The function I want in the future is to receive memo and automatically store my own vector data, so that I can customize and implement semantic search. I can also summarize daily notes regularly, llm can summarize, review everything today, and discover after using it. n8n There are really many possibilities

**Comment by blinko-space** [comment]
supported at v0.19.1

**Comment by LiangWei88** [comment]
> supported at v0.19.1

太棒啦!
