### ISSUE TITLE
I want to add a new language to translations

### ISSUE THREAD

**Issue by SerhiiZahuba** [blinko-space/blinko#239]
Hello.

 Please write how to add a new translation language to the project. Thank you

**Comment by blinko-space** [comment]
What languages do you want to support? you can clone this project and add a new JSON file for your language in the public/locales directory. For example, if you're adding French, you might create public/locales/fr/translation.json.

and ensure that the new language is included in the i18next configuration. This might involve updating the src/lib/i18n.ts file to include your new language, although specific instructions for this step are not available in the current documentation.
