### ISSUE TITLE
希望能支持更多的AI || Hope to support more AI

### ISSUE THREAD

**Issue by eshugou** [blinko-space/blinko#248]
希望能支持与智谱清言、讯飞星火、阿里通义、百度文心一言、抖音豆包、腾讯混元、kimi等中国AI平台

---
Hope to support Chinese AI platforms such as Zhipu Qingyan, iFlytek Spark, Alibaba Tongyi, Baidu Wenxinyiyan, Douyin Doubao, Tencent Hunyuan, kimi and other Chinese AI platforms

**Comment by BryceWG** [comment]
所有支持openai格式的ai都能使用,据我所知你上面提到的可能只有讯飞是不支持的
