### ISSUE TITLE
希望支持makedown表格、流程图、思维导图、Echarts图形图表、科学公式等功能 || Hope to support makedown tables, flow charts, mind maps, Echarts graphics charts, scientific formulas and other functions

### ISSUE THREAD

**Issue by eshugou** [blinko-space/blinko#249]
希望支持makedown表格、流程图、思维导图、Echarts图形图表、科学公式等功能，我今天测试过，最新版本无法支持表格、流程图、思维导图、Echarts图形图表、科学公式。

---
I hope to support makedown tables, flow charts, mind maps, Echarts graphics charts, scientific formulas and other functions. I tested it today and the latest version cannot support tables, flow charts, mind maps, Echarts graphics charts, scientific formulas.

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/a139d862-253d-43d2-abb2-dfefb087d656)
v0.20.0已经支持
