### ISSUE TITLE
建议输入框增加一下隐藏显示UI的开关选项 || It is recommended to add a switch option to hide and display the UI in the input box.

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#253]
![image](https://github.com/user-attachments/assets/4d1b1db6-5ea5-48f4-a608-cf43154abeec)

请问是否可以增加个开关，隐藏顶部栏markdown相关的图标，感觉还是之前的输入框比较简洁，现在的信息密度有点大。
因为若是可以隐藏的话，对于习惯性渲染输出markdown文章的人来说，没什么障碍。

![image](https://github.com/user-attachments/assets/f8c54d05-b229-47c3-ad55-75425c83d37b)

或者大佬也可以考虑一下，直接把这些功能添加到右键菜单里，选中文字，右键提供相关的功能选择。

---
![image](https://github.com/user-attachments/assets/4d1b1db6-5ea5-48f4-a608-cf43154abeec)

I would like to ask if you can add a switch to hide the markdown related icons in the top bar. I feel that the previous input box is relatively simple, but now the information density is a bit high.
Because if it can be hidden, there will be no obstacle for people who are accustomed to rendering and outputting markdown articles.

![image](https://github.com/user-attachments/assets/f8c54d05-b229-47c3-ad55-75425c83d37b)

Or you can consider adding these functions directly to the right-click menu, select the text, and right-click to provide relevant function selections.

**Comment by BryceWG** [comment]
感觉可以加一个展开收起按钮在上面那一行

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/25175389-7873-4e9e-b036-30de4689e517)
