### ISSUE TITLE
Can't save any notes after updating to v0.18.6

### ISSUE THREAD

**Issue by dhanadhan** [blinko-space/blinko#255]
Hi, 

I noticed that the Docker Compose file doesn't specify any volume. 
I'm currently using "./blinko:/app/.blinko", and it was working fine until the recent update. Now that I just updated the container, I can't save any notes — the save button doesn't seem to work. I checked the container logs, but there's nothing unusual there. Has the app's data folder path changed, or is it still the same?

Thanks

**Comment by SiJin233** [comment]
Same question. 😢

**Comment by MingYanYu** [comment]
Same.It only works properly when using the CTRL + ENTER shortcut key. The button is not working.

**Comment by lxk1066** [comment]
In mobile browsers you can click the button to save, but in pc browsers you can only save via shortcuts.

**Comment by blinko-space** [comment]
yes,this is ui issue ,has been fixed in  https://github.com/blinko-space/blinko/releases/tag/v0.19.0
