### ISSUE TITLE
图片404 || Picture 404

### ISSUE THREAD

**Issue by fantasyzyc** [blinko-space/blinko#259]
![image](https://github.com/user-attachments/assets/7fcb6d6d-42f9-4d1a-8f3b-3895fc36316c)
1、memos导入后,图片单独导入到files文件夹,postgres中核对文件名后,依然无法正确找到图片文件
2、正常编辑界面上传图片ok，尝试在postgres中修改path，改回后就404

---
![image](https://github.com/user-attachments/assets/7fcb6d6d-42f9-4d1a-8f3b-3895fc36316c)
1. After memos is imported, the pictures are imported separately into the files folder. After checking the file names in postgres, the picture files still cannot be found correctly.
2. Uploading pictures in the normal editing interface is ok. Try to modify the path in postgres. After changing it back, it will be 404

**Comment by blinko-space** [comment]
可以提供files文件夹内的截图文件名和postgres的截图吗

**Comment by fantasyzyc** [comment]
![image](https://github.com/user-attachments/assets/f1ecce07-30bd-45ce-abd3-a4b87938c155)
![image](https://github.com/user-attachments/assets/51deb55e-898d-4fce-b748-65e07ca934fb)
![image](https://github.com/user-attachments/assets/2306d8fc-2c64-4ae7-8878-e64d24d8ff7f)


> 可以提供files文件夹内的截图文件名和postgres的截图吗
> 
> Can you provide the screenshot file name in the files folder and the screenshot of postgres
