### ISSUE TITLE
希望可以支持md的时序图格式 || I hope the md timing diagram format can be supported.

### ISSUE THREAD

**Issue by CiZaii** [blinko-space/blinko#262]
<img width="574" alt="image" src="https://github.com/user-attachments/assets/b797a2fe-3aee-4e25-bbf2-c20304d69fa7">
现在是不支持的我看

---
<img width="574" alt="image" src="https://github.com/user-attachments/assets/b797a2fe-3aee-4e25-bbf2-c20304d69fa7">
It is not supported now. I think

**Comment by BryceWG** [comment]
mermaid?

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/53a5a35c-66f9-444a-bac7-8199bdf6c66e)
v0.20.0已经支持
