### ISSUE TITLE
移动端PWA的状态栏取色问题，或许调整一下效果会更好 || The status bar color selection problem of mobile PWA, maybe the effect will be better if it is adjusted

### ISSUE THREAD

**Issue by dsu-k** [blinko-space/blinko#265]
它或许不应称为bug，但是不显突兀的状态栏颜色能更好的带来页面沉浸感。

![Screenshot_20241208_232041](https://github.com/user-attachments/assets/6f3f9855-197b-4791-8821-32df3261449c)
![Screenshot_20241208_232025](https://github.com/user-attachments/assets/256e3a26-5d84-4faf-863c-89c095e628e1)

---
It probably shouldn't be called a bug, but the unobtrusive color of the status bar can better bring immersion to the page.

![Screenshot_20241208_232041](https://github.com/user-attachments/assets/6f3f9855-197b-4791-8821-32df3261449c)
![Screenshot_20241208_232025](https://github.com/user-attachments/assets/256e3a26-5d84-4faf-863c-89c095e628e1)

**Comment by BryceWG** [comment]
电脑端PWA的状态栏也是黑色
![gxfsx12v o2w](https://github.com/user-attachments/assets/3ed70c91-2506-4176-b88f-15a8b849078e)

**Comment by BryceWG** [comment]
顺便问一下你这个PWA是用什么浏览器制作的

**Comment by dsu-k** [comment]
> 顺便问一下你这个PWA是用什么浏览器制作的
> 
> By the way, what browser did you use to create this PWA?

chrome

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/bc32b260-779c-461c-8118-3eb84410684c)
确实如此
![image](https://github.com/user-attachments/assets/1080d9db-4828-42c3-83f4-14247a3393be)
Memos 就比较统一协调
