### ISSUE TITLE
资源页面是搜索没办法选中输入 || The resource page is in search mode and there is no way to select and enter it.

### ISSUE THREAD

**Issue by jingshaoxiang** [blinko-space/blinko#267]
![QQ_1733715046073](https://github.com/user-attachments/assets/d9677645-24a8-4819-bc9a-2208a4985468)

---
![QQ_1733715046073](https://github.com/user-attachments/assets/d9677645-24a8-4819-bc9a-2208a4985468)

**Comment by blinko-space** [comment]
v0.21.15 fixed
