### ISSUE TITLE
资源文件删除失败 || Resource file deletion failed

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#269]
**Describe the bug**
笔记中和资源管理页面中删除资源文件均会失败

**To Reproduce**
![PixPin_2024-12-09_14-54-42](https://github.com/user-attachments/assets/5d8878e7-1237-48f3-936e-7f2d960411f7)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version v0.20.5

---
**Describe the bug**
Deleting resource files in notes and resource management pages will fail.

**To Reproduce**
![PixPin_2024-12-09_14-54-42](https://github.com/user-attachments/assets/5d8878e7-1237-48f3-936e-7f2d960411f7)

**Desktop (please complete the following information):**
 -OS: Windows11
 -Browser chrome
 - Version v0.20.5

**Comment by blinko-space** [comment]
最新版已修复
