### ISSUE TITLE
手机端页面优化适配

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#27]
![image](https://github.com/user-attachments/assets/5f74b7c6-5aeb-47e3-8e7f-2de57d747576)

大佬，再提一个优化项。
就是在手机端使用Safari浏览器把页面添加到主屏幕以后，
然后再屏幕上点击Blinko图标，进入的页面依然是Safari浏览器的外观，就是下方的地址栏还是存在的。
而不是类似手机APP的形式来显示。

**Comment by blinko-space** [comment]
move to https://github.com/blinko-space/blinko/issues/42
