### ISSUE TITLE
mermaid渲染图查看时尺寸过小 || The size of the mermaid rendering is too small when viewed

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#270]
**Describe the bug**
mermaid渲染图查看时尺寸过小,图片点击时尺寸较为正常.

**To Reproduce**
![PixPin_2024-12-09_14-57-11](https://github.com/user-attachments/assets/5e9a7929-bb58-4243-bf8b-ea3e1be991b7)

**Expected behavior**
mermaid渲染图能够与正常图片一样大小

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version v0.20.5

---
**Describe the bug**
The size of the mermaid rendering is too small when viewed, but the size is normal when clicked.

**To Reproduce**
![PixPin_2024-12-09_14-57-11](https://github.com/user-attachments/assets/5e9a7929-bb58-4243-bf8b-ea3e1be991b7)

**Expected behavior**
Mermaid renderings can be the same size as normal images

**Desktop (please complete the following information):**
 -OS: Windows11
 -Browser chrome
 - Version v0.20.5

**Comment by blinko-space** [comment]
可以放大缩小的

**Comment by BryceWG** [comment]
懂了哈哈
