### ISSUE TITLE
S3 issue

### ISSUE THREAD

**Issue by smallxi** [blinko-space/blinko#276]
1，S3上传同名文件，后面上传的会把前面的覆盖。
2，资源页面删除文件后，S3上的会被删除，但是资源页面上并没有删除
3，S3的文件能否用自定义的域名（配置了的CDN域名）访问

---
1. If you upload a file with the same name to S3, the later upload will overwrite the previous one.
2. After deleting the file on the resource page, it will be deleted on S3, but it will not be deleted on the resource page.
3. Can S3 files be accessed using a custom domain name (configured CDN domain name)

**Comment by blinko-space** [comment]
1和2已经修复
