### ISSUE TITLE
AI Tags seems broken

### ISSUE THREAD

**Issue by tcsenpai** [blinko-space/blinko#277]
**Describe the bug**
Generating AI tags result in a sentence (often multi line) instead of just tags.
Additionally, tags are then introduced within markdown contents resulting in H1 titles instead of actual tags.

**To Reproduce**
Generate AI tags for a Blinko

**Expected behavior**
Get a list of tags

**Screenshots**
![image](https://github.com/user-attachments/assets/b72d861e-a111-4e19-88dd-0c22e6523516)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Zen (Firefox)
 - Version latest
 
**Additional context**
Using default AI settings with Ollama and llama3.2

**Comment by tcsenpai** [comment]
Great to have a bot replying, just bumping this to ensure an human will actually read it

**Comment by blinko-space** [comment]
Optimized the  prompt. It should be more stable now.
