### ISSUE TITLE
无法加载更多笔记内容 || Unable to load more note content

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#278]
![image](https://github.com/user-attachments/assets/3c732eb4-5ae6-4016-a1c5-ad1217083930)

大概有700多条笔记，但是鼠标滚轮向下滚动，也无法加载更多笔记内容。
使用的是chrome，尝试刷新页面，重新登陆账号以及使用无痕模式登录，问题依然存在。
之前也遇到过一两次，偶现问题。
请大佬看一看。

---
![image](https://github.com/user-attachments/assets/3c732eb4-5ae6-4016-a1c5-ad1217083930)

There are probably more than 700 notes, but scrolling down with the mouse wheel cannot load more notes.
I am using Chrome. I tried refreshing the page, logging in again and using incognito mode, but the problem still exists.
I've encountered it once or twice before, with occasional problems.
Please take a look, sir.

**Comment by blinko-space** [comment]
你这个屏幕我估计有一米多长

**Comment by i-iooi-i** [comment]
> 你这个屏幕我估计有一米多长
> 
> I estimate your screen is over one meter long

并没有，液晶显示器 飞利浦 278B（27寸/ 4K/ 无Type-C/ 配HDMI、DP、Type-C转DP）

**Comment by blinko-space** [comment]
主要问题是 首次加载的笔记数量达不到触发滚动条的数量 导致没法滚动加载 我优化一下

**Comment by i-iooi-i** [comment]
> 你这个屏幕我估计有一米多长
> 
> I estimate your screen is over one meter long

使用筛选工具，就可以自动加载出更多的笔记内容的。
但是笔记页面就是没有反应。🙈


这个单子可以先挂着，看看有没有人遇到过类似的问题。

**Comment by blinko-space** [comment]
你可以尝试ctrl+滚轮放大出滚动条 然后就可以加载了

**Comment by i-iooi-i** [comment]
> 你可以尝试ctrl+滚轮放大出滚动条 然后就可以加载了
> 
> You can try ctrl+scroll wheel to enlarge the scroll bar and then load

![image](https://github.com/user-attachments/assets/a0da0801-7adc-48cb-a80b-4ea1a18ca4bc)
还真是，把页面放大，就可以触发滚动出更多的内容辣。
蟹蟹大佬 🌹🌹

**Comment by blinko-space** [comment]
增加了页码设置
![image](https://github.com/user-attachments/assets/6af62644-b727-4cf1-994c-263f57dbb4d2)
