### ISSUE TITLE
Memos数据库导入后代码块没有复制按钮 || There is no copy button for the code block after importing the Memos database

### ISSUE THREAD

**Issue by WyInnovate** [blinko-space/blinko#279]
问题如标题所示，刚刚导入不做任何操作的话，代码块的复制按钮没有，编辑后保存即可显示
新建的代码块没有问题

---
The problem is as shown in the title. If you just imported it without doing any operations, there will be no copy button for the code block. It will be displayed after editing and saving.
There is no problem with the newly created code block

**Comment by blinko-space** [comment]
试了从memos导入没有问题有复制按钮 可以提供一下memos里面的代码片段吗

**Comment by WyInnovate** [comment]
> 试了从memos导入没有问题有复制按钮 可以提供一下memos里面的代码片段吗
> 
> I tried importing from memos and there was no problem. There is a copy button. Can you provide a code snippet from memos?

比如这个
![image](https://github.com/user-attachments/assets/c31805c6-fd1f-4819-b991-ece85a43a737)
数据表里存的内容是如下：
```
#备份 
# 头像链接
```
https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvdXBsb2FkZWQvaW1nXzJudW9vSTdFWTJIblJkcHhoMkdOYnFhcXFUNyJ9
```
```
