### ISSUE TITLE
功能建议：希望利用鼠标双击功能对单条笔记做一些拓展

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#28]
![image](https://github.com/user-attachments/assets/301854c0-aa01-4700-b83d-13fb2685390e)

大佬是否考虑当使用鼠标对着某条框内的笔记双击的时候，实现复制功能，或者实现编辑功能。
这样操作效率会高不少。目前复制笔记要先选中笔记，再快捷键复制，当要快速处理多条笔记的时候还是比较低效的。
当然，编辑功能也是类似问题，鼠标无形中要多点一下。

**Comment by blinko-space** [comment]
感谢你的建议该功能已经添加[new feature](https://github.com/blinko-space/blinko/tree/%2328-new-feature)
