### ISSUE TITLE
 api接口 get user tags 请求报错 404

### ISSUE THREAD

**Issue by taklele** [blinko-space/blinko#283]
**Describe the bug**
<img width="587" alt="SCR-20241211-hssn" src="https://github.com/user-attachments/assets/53f93282-41f1-4012-bca8-5a8d4a8f5654">

当前版本：v0.22.1

辛苦修复，谢谢

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/fd43d1e2-20af-4855-81a2-f12a3af6076f)
请问你是什么版本我本地测试可以 http://localhost:1111/api/v1/tags/list

**Comment by taklele** [comment]
0.22.1
<img width="524" alt="image" src="https://github.com/user-attachments/assets/48d2e749-ac8e-4c9c-922e-a25d71c11695">

**Comment by blinko-space** [comment]
你完整的请求url是什么？

**Comment by taklele** [comment]
果然是请求地址搞错了。
之前都是参考文档写的代码，请求地址类似 https://blinko.apidocumentation.com/v1/tags/list 
实际应是 https://blinko.apidocumentation.com/**api/**v1/tags/list
多谢多谢
