### ISSUE TITLE
提供一份未汉化列表 || Provided Yifeng Weihua List

### ISSUE THREAD

**Issue by manjieqi** [blinko-space/blinko#284]
About
Upload
local
Days
Select Model Provider
Select Model
Embedding Model
Create User
Allow Register
Access Token
Webhook
Bucket
Region
Endpoint
Access key secret
Access key id
Share and copy link
Insert image

---
About
Upload
local
Days
Select Model Provider
Select Model
Embedding Model
Create User
Allow Register
Access Token
Webhook
Bucket
Region
Endpoint
Access key secret
Access key id
Share and copy link
Insert image

**Comment by blinko-space** [comment]
已经更新了汉化
