### ISSUE TITLE
Add proxy setting for API request

### ISSUE THREAD

**Issue by SneakyTurt1e** [blinko-space/blinko#285]
Do we have any plan about to add proxy setting?

I think adding a proxy is a very good option for countries/regions/env. that cannot directly access the API.

**Comment by blinko-space** [comment]
I'm sorry, there's no such program at the moment, if you mean openapi is inaccessible, there are plenty of proxy api services on the market.

**Comment by BryceWG** [comment]
Why not use a transit service?
