### ISSUE TITLE
PostgreSQL中附件path与files的关系问题 || The relationship between attachment paths and files in PostgreSQL

### ISSUE THREAD

**Issue by fantasyzyc** [blinko-space/blinko#286]
一直没搞明白一个问题，想请教：
当前是docker环境
我在files目录中手动上传1.png，然后在PostgreSQL中attachments表中，path改为/api/file/1.png，但是该笔记图片就显示404，而不是上传的1.png那张图片；

API接口也返回404
{
    "Message": "File not found",
    "status": 404
}

---
I have never understood a question and would like to ask:
Currently it is docker environment
I manually uploaded 1.png in the files directory, and then changed the path to /api/file/1.png in the attachments table in PostgreSQL, but the note image displayed 404 instead of the uploaded 1.png image;

The API interface also returns 404
{
    "Message": "File not found",
    "status": 404
}

**Comment by blinko-space** [comment]
你的逻辑没有问题 可能是操作的时候出现了问题

**Comment by blinko-space** [comment]
files目录下的文件和attachments内的path是一一对应的关系
