### ISSUE TITLE
hashtag has still a bug

### ISSUE THREAD

**Issue by swinxx** [blinko-space/blinko#291]
Thank you for your hard work and fast improvements! 

the hashtag bugs are nearly fixed now. but there is still one weird thing..
so i will try to explain as good as i can, and will add a video for better understanding: 

please change the behaviour blinko uses for searching existing hashtags in new notes/blinkos.

lets say there is an existing hashtag like #myhashtag/fun 
which is a subdirectory "fun" in the register "myhashtag. perfect.

https://github.com/user-attachments/assets/b91cd8a1-365b-47f1-be4b-5af18f52f6f2

when i type "#un".. blinko will list and use #myhashtag/fun, because "un" is part of the word "fun". 
what if i want to add #fun without #myhashtag? probably restrict the search to an accurate order

**Comment by blinko-space** [comment]
now fixed in latest version
