### ISSUE TITLE
中文名称的图片会404|The image with the Chinese name will be 404.

### ISSUE THREAD

**Issue by 3546475** [blinko-space/blinko#292]
When the uploaded image name contains Chinese characters, it will be inaccessible.
当上传的图片名称中带有中文时，将无法访问。

The three uploaded images are the same image, but with different names.
上传的这三张是同一个图片，但名称不同。
![image](https://github.com/user-attachments/assets/bc0669f9-08a6-4511-b2aa-e8d27b1e5c1d)

**Comment by i-iooi-i** [comment]
相同问题~
