### ISSUE TITLE
update.sh资源会丢失 || update .sh resources will be lost

### ISSUE THREAD

**Issue by smallxi** [blinko-space/blinko#293]
作者开发的程序很强大，很喜欢！
更新频率非常高，我不知道如何去更新，目前是docker部署，运行update.sh去更新，但是这么更新资源库会丢失，请问这是bug吗，还是我更新方式不对

---
The program developed by the author is very powerful, I like it very much!
The update frequency is very high. I don’t know how to update. Currently, it is deployed with docker. Run update.sh to update, but the resource library will be lost when updating like this. Is this a bug? Or am I updating the wrong way?

**Comment by smallxi** [comment]
请问该怎么绑定。我是通过这个安装的程序curl -s https://raw.githubusercontent.com/blinko-space/blinko/main/install.sh | bash

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/3c4ab3cf-5920-430c-9d1d-bb6cbb7c3f27)
安装的时候就有提示
