### ISSUE TITLE
无法用键盘选取tag并添加 || Cannot select tag and add using keyboard

### ISSUE THREAD

**Issue by a15355447898a** [blinko-space/blinko#298]
**Describe the bug**
我想要通过键盘选取tag,通过方向键上下选择后,回车就能得到选择了的tag
但是目前回车后不会得到任何东西

**To Reproduce**
1. 编辑一个卡片
2. 选择tag
3. 回车

**Expected behavior**
回车后应该可以得到选择了的tag

**Screenshots**

https://github.com/user-attachments/assets/1daec840-98ab-4530-84fd-1366c48a997d

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version: v0.24.3

**Additional context**

---
**Describe the bug**
I want to select a tag through the keyboard. After selecting up and down using the arrow keys, press Enter to get the selected tag.
But currently you won’t get anything after pressing Enter

**To Reproduce**
1. Edit a card
2. Select tag
3. Enter

**Expected behavior**
After pressing Enter, you should be able to get the selected tag.

**Screenshots**

https://github.com/user-attachments/assets/1daec840-98ab-4530-84fd-1366c48a997d

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version: v0.24.3

**Additional context**

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)
