### ISSUE TITLE
夜间模式，笔记编辑状态，链接颜色不可见。

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#30]
https://github.com/user-attachments/assets/e8d22357-e474-48ed-b51e-2ee82204cfe3

当使用夜间模式编辑笔记的时候，笔记内的链接颜色过暗，导致不可见。

**Comment by blinko-space** [comment]
![image](https://github.com/user-attachments/assets/c5c6d7f2-c76d-40fd-ab80-ae6e72d940b4)
这个在最新版本中sh是被修复了的

**Comment by i-iooi-i** [comment]
> ![image](https://private-user-images.githubusercontent.com/186030902/384650528-c5c6d7f2-c76d-40fd-ab80-ae6e72d940b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTgwODksIm5iZiI6MTczMTIxNzc4OSwicGF0aCI6Ii8xODYwMzA5MDIvMzg0NjUwNTI4LWM1YzZkN2YyLWM3NmQtNDBmZC1hYjgwLWFlNmU3MmQ5NDBiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNTQ5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTdjZTA3MTUyZjA3ZWQ3ZTdlYjQ3YTU5Y2FlYWYwYTBlNWUyMjgxN2E4NDQ0MWIxMDYxNWEyOGI2N2MwODExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bhWJUI7SJi1ZRE4YnU66aMW3mdqesvLuW8XcUJEIPFQ) 这个在最新版本中sh是被修复了的

不是笔记文字，是链接文字的，链接文字会很暗，看不清的。
![image](https://github.com/user-attachments/assets/f8d2071a-1d68-431b-9cc9-f013ebf5130b)
![image](https://github.com/user-attachments/assets/aff56114-3fd3-467a-9433-1927b475adda)
