### ISSUE TITLE
笔记折叠后 # 标签失效 || The # tag becomes invalid after the note is folded

### ISSUE THREAD

**Issue by StormPhoenix** [blinko-space/blinko#300]
文本折叠长度从 500 修改为 200 后发现，长度超过 200 的笔记折叠后，#标签变成了黑粗字体，而非标签样式。
<img width="920" alt="Snipaste_2024-12-13_19-56-12" src="https://github.com/user-attachments/assets/e44593bb-b890-438b-a452-e1477612cee6" />

---
After changing the text folding length from 500 to 200, we found that after folding notes longer than 200, the #tag became a bold black font instead of the tag style.
<img width="920" alt="Snipaste_2024-12-13_19-56-12" src="https://github.com/user-attachments/assets/e44593bb-b890-438b-a452-e1477612cee6" />

**Comment by StormPhoenix** [comment]
版本是 v0.24.3

**Comment by blinko-space** [comment]
这是一个特性 过滤掉标题的符号 让其更加美观 真正的标签在下方，建议#标签 然后换行输入标题 或者标签放到最下方
