### ISSUE TITLE
The simplest Markdown format content presentation still has many problems

### ISSUE THREAD

**Issue by luowei** [blinko-space/blinko#302]
**Describe the bug**
The simplest Markdown format content presentation still has many problems

**To Reproduce**
use the follow simple markdown text 
```
#### 最简单的 Markdown 格式内容显示还是有很多问题！！
  
#### 局域网内启用 mDNS, 以使用 `.local` 域名

在局域网内启用 mDNS（多播 DNS）协议， 以便使用 `.local` 域名，Debian 通常预装并启用了 `Avahi` 服务（mDNS 服务），而 Ubuntu 的 `Avahi` 可能未正确配置或未启用。

1. 检查主机名：`hostnamectl`，设置主机名： `sudo hostnamectl set-hostname pven100-ubuntu`；
2. 检查 `/etc/hosts` 文件，确保主机名正确映射到本地主机：`sudo vim /etc/hosts`, 并确保有以下条目：`127.0.1.1 pven100-ubuntu`；
3. 启用 mDNS 服务（Avahi）
   1. 先检查是否安装 Avahi：`dpkg -l | grep avahi-daemon`，`sudo apt install avahi-daemon`；
   2. 启动并启用 Avahi 服务：`sudo systemctl enable --now avahi-daemon`, `sudo systemctl status avahi-daemon`；
   3. 检查 mDNS 功能, 使用命令 `ping pven100-ubuntu.local` 确认目标主机是否能够解析自己的 `.local` 地址;
4. 检查网络和防火墙设置, 确保 UDP 5353 端口未被阻止:`sudo ufw allow from any to any port 5353 proto udp`； 确认 mDNS 通信，在任意一台主机上运行： `avahi-browse -a`； 使用 avahi-browse 需安装 avahi-utils：`apt install avahi-utils`；

**参考：**

[Avahi - 轻松实现局域网中的.local域名服务](https://cloud.tencent.com/developer/article/2376629)

\#homelab
```
**Current**: https://blinko-demo.vercel.app/share/252

**Expected behavior**
![image](https://github.com/user-attachments/assets/23a65527-e126-4539-9f2a-a640329aae52)

**Screenshots**
![image](https://github.com/user-attachments/assets/e80482a1-bdc3-40bc-8011-89bdea6ff8b7)

**Desktop (please complete the following information):**
 - OS: Chrome web browser
 - Browser chrome, safari
 - Version v0.25.3

**Smartphone (please complete the following information):**
 - All Same with Desktop

**Additional context**

**Comment by blinko-space** [comment]
这个只是把行内代码块识别成了块级代码 现在修复了
