### ISSUE TITLE
在ai计算嵌入时发现有默认数据残留 || Default data residue was found when AI calculated embedding

### ISSUE THREAD

**Issue by LiangWei88** [blinko-space/blinko#309]
**Describe the bug**
自己docker部署了一个服务, 最近将旧的删掉了, 重新部署了 0.25.6版本, 刚进去看到一些demo笔记, 一两秒自动跳转, 必须注册登录才能进入页面.
当我注册账号, 登录之后, 所有 demo 笔记都不见了, 但是当我设置好 ai 配置, 建立 faiss 索引时, 总是有 demo 数据如 #welcome 等等, 但是这些笔记是搜索不到的.

**To Reproduce**
1. 以前部署过, 登陆过, 页面还在打开
2. 删除了服务器的 docker container, 重新部署
3. 在页面上重新刷新, 看见一瞬间首页, 然后调到登录页
4. 重新注册登录, 进入之后是完全空白的系统
5. 导入 memos 笔记
6. 设置 ai
7. 强制重建索引

**Expected behavior**
要么能看到demo笔记, 我自己删除, 要么不存在的笔记不应该被索引

**Screenshots**
![image](https://github.com/user-attachments/assets/a651afaf-c8e2-4388-b697-c1f2e1d99685)

**Desktop (please complete the following information):**
 - OS: aliyun ubuntu
 - Browser chrome
 - Version 0.25.6

---
**Describe the bug**
I deployed a service with docker myself. I recently deleted the old one and redeployed version 0.25.6. I just entered and saw some demo notes. It automatically jumped in a second or two. You must register and log in to enter the page.
When I registered an account and logged in, all the demo notes disappeared. However, when I set up the ai configuration and established the faiss index, there was always demo data such as #welcome, etc., but these notes could not be searched.

**To Reproduce**
1. It has been deployed before, logged in, and the page is still open.
2. Delete the docker container of the server and redeploy it
3. Refresh the page, see the homepage for a moment, and then switch to the login page
4. Register and log in again. After entering, the system will be completely blank.
5. Import memos notes
6. Set up AI
7. Force index rebuild

**Expected behavior**
Either I can see the demo notes and delete them myself, or the non-existent notes should not be indexed.

**Screenshots**
![image](https://github.com/user-attachments/assets/a651afaf-c8e2-4388-b697-c1f2e1d99685)

**Desktop (please complete the following information):**
 - OS: aliyun ubuntu
 -Browser chrome
 - Version 0.25.6

**Comment by smallxi** [comment]
我也有这个情况，你可以试试重启容器，看下能不能看见内容，然后将它们删除即可

**Comment by LiangWei88** [comment]
> 我也有这个情况，你可以试试重启容器，看下能不能看见内容，然后将它们删除即可
> 
> I also have this situation, you can try restarting the container, see if you can see the content, and then delete them

说的对, 发现新部署的注册新用户后, 要重启才看到 demo 笔记
