### ISSUE TITLE
在笔记的二次编辑状态无法插入标签

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#31]
https://github.com/user-attachments/assets/81627c96-54a1-4658-8803-11bbd41f3e40

当二次编辑笔记的时候，无法在笔记顶部插入新的标签。

**Comment by blinko-space** [comment]
fixed https://github.com/blinko-space/blinko/commit/8d14f89ce4e54105ee6e021b185ed2ce8fadcffa
