### ISSUE TITLE
[Security Risk?] Backup file can be downloaded without logging in.

### ISSUE THREAD

**Issue by JasonGrass** [blinko-space/blinko#313]
**Describe the bug**

During local testing, I found that it is possible to download the backup file directly from the following URL, even without logging in:

http://localhost:1111/api/file/blinko_export.bko

This may indicate some security risks with the site. I'm unsure if this issue will occur when deployed on a server. However, I did not encounter this problem using the demo site: https://blinko-demo.vercel.app/api/file/blinko_export.bko.

**Desktop (please complete the following information):**
version v0.25.6

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)
now only superadmin can download .bko file
