### ISSUE TITLE
点击正文中的标签无法筛选 || Clicking tags in the text cannot filter

### ISSUE THREAD

**Issue by fantasyzyc** [blinko-space/blinko#315]
侧边栏可以，但点击正文的标签点击后，地址栏有变化，但内容不筛选
![image](https://github.com/user-attachments/assets/57effa49-ac4f-4527-b08a-2c086dcf3810)

---
The sidebar is OK, but after clicking on the label of the text, the address bar changes, but the content is not filtered.
![image](https://github.com/user-attachments/assets/57effa49-ac4f-4527-b08a-2c086dcf3810)

**Comment by blinko-space** [comment]
fixed in [ea77bed](https://github.com/blinko-space/blinko/commit/ea77bed5d1426d5433e7a0c161d650c1369cc0ae)
