### ISSUE TITLE
在mac平台上无法粘贴复制的文本 || Unable to paste copied text on mac platform

### ISSUE THREAD

**Issue by x2358473** [blinko-space/blinko#318]
使用docker部署完，发现只能输入。无法进行粘贴文本内容。

---
After deploying using docker, I found that I could only enter. Unable to paste text content.

**Comment by x2358473** [comment]
在pc端的浏览器中设置成移动端模式就能进行粘贴。

**Comment by x2358473** [comment]
在pc端的pc模式进行ctrl+v 时报错了
<img width="829" alt="image" src="https://github.com/user-attachments/assets/9e6f76f3-772c-450c-8997-c3b119bfa86d" />

**Comment by blinko-space** [comment]
这个问题在v0.26.1 已经修复了
