### ISSUE TITLE
md链接图片排版优化 || md link image layout optimization

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#320]
**Is your feature request related to a problem? Please describe.**

当多张尺寸大小不一的图片在一个note下,尤其存在长截图时,当前的卡片展示非常影响阅读体验.

**Describe the solution you'd like**

1. 可参考微信朋友圈的1-9张图的设计

**Describe alternatives you've considered**

**Additional context**

---
**Is your feature request related to a problem? Please describe.**

When multiple pictures of different sizes are placed under one note, especially when there are long screenshots, the current card display greatly affects the reading experience.

**Describe the solution you'd like**

1. You can refer to the design of pictures 1-9 in WeChat Moments.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jonnyan404** [comment]
对于超过指定像素宽高的图片,可以简单粗暴的等比缩放到指定大小

**Comment by blinko-space** [comment]
最新版本限制了高度
