### ISSUE TITLE
剪贴板图片上传作为附件上传,关闭vditor编辑器的源链接md引用 || Upload the clipboard image as an attachment, close the source link md reference of the vditor editor

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#325]
**Is your feature request related to a problem? Please describe.**

同主站的情况下,上传图片会被vditor编辑器以md引用源链接的形式注入文档内容. 而我需要图片作为附件展示

**Describe the solution you'd like**

关闭vditor编辑器的原始图片链接引用

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/2895866d-6c01-4e08-8210-44fb29c9a175)

---
**Is your feature request related to a problem? Please describe.**

In the case of the same main site, the uploaded image will be injected into the document content in the form of md reference source link by the vditor editor. And I need the image to be displayed as an attachment.

**Describe the solution you'd like**

Turn off the original image link reference of the vditor editor

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/2895866d-6c01-4e08-8210-44fb29c9a175)

**Comment by blinko-space** [comment]
v0.27.2 is now support
