### ISSUE TITLE
Follow System Theme by default.

### ISSUE THREAD

**Issue by accforgithubtest** [blinko-space/blinko#326]
Hello

Even though #219 is closed, it looks like blinko is still using light theme as default, which means I have to goto settings each time and change it follow system theme.

Can blinko follow system theme by default ?
That way, user system settings are automatically followed, without having to change in settings each and every time.

**Comment by DLHTX** [comment]
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/9f1cf567-0841-4b0b-80d9-78987bcdf4df" />
you can set follow system

**Comment by accforgithubtest** [comment]
Thanks for the reply.

Current issue is that it is setting light them by default and my request here is that 'Follow System' should be the default setting.

For users that prefer to use dark theme system wide as first preference, right now it is always a extra step as soon as I start blinko to go and set the theme.

If `Follow system` is set as the default, then blinko will automatically follow the users preferences from the OS/Browser.
This will help users that prefer either light and dark theme and just follow the system theme as default.

**Comment by blinko-space** [comment]
v0.27.2 is now support
