### ISSUE TITLE
S3 CORS

### ISSUE THREAD

**Issue by linzeliang0138** [blinko-space/blinko#327]
**Describe the bug**
After upgrading from 0.25.6 to 0.26.10, S3 uses Cloudflare R2. The pictures displayed in the notes cannot be displayed due to CORS issues, but you can view them normally by clicking on the pictures to enlarge them.

**To Reproduce**
1. Write blinko or notes
2. Upload picture file
3. Publish
4. Refresh
5. Picture 404

**Expected behavior**
Pictures display normally

**Screenshots**
![image](https://github.com/user-attachments/assets/50434dee-73ad-4e25-8a75-7780feae570f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blinko-space** [comment]
fixed in v0.27.2
