### ISSUE TITLE
上传附件后,删除任意一个附件,会导致编辑框整个退出,内容丢失 || After uploading attachments, deleting any attachment will cause the entire edit box to exit and the content to be lost.

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#332]
**Describe the bug**

上传附件后,删除任意一个附件,会导致编辑框整个退出,内容丢失

**To Reproduce**
1. 编辑内容
2. 上传附件
3. 删除附件

**Expected behavior**

删除附件,仅从当前附件列表里删除选中的附件.
不是清空整个编辑框

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---
**Describe the bug**

After uploading attachments, deleting any attachment will cause the entire edit box to exit and the content to be lost.

**To Reproduce**
1. Edit content
2. Upload attachments
3. Delete attachments

**Expected behavior**

Delete attachments, only delete the selected attachments from the current attachment list.
Does not clear the entire edit box

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blinko-space** [comment]
fixed in v0.27.2
