### ISSUE TITLE
上传附件后,可拖动来调整顺序 || After uploading attachments, you can drag them to adjust the order.

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#333]
**Is your feature request related to a problem? Please describe.**

当上传多张图片时,前后顺序不对时,需要拖动来调整

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
**Is your feature request related to a problem? Please describe.**

When uploading multiple pictures, if the order is wrong, you need to drag to adjust.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by blinko-space** [comment]
v0.27.2 is now support
