### ISSUE TITLE
2FA ignored for login and other account settings

### ISSUE THREAD

**Issue by no8ody** [blinko-space/blinko#338]
Today I logged in with my account from a different and external device. I noticed that despite 2FA being activated, the login can be carried out without a corresponding query. This is a major security risk and should be fixed asap. Also, settings such as theme and language are apparently not applied.

**Comment by blinko-space** [comment]
I'm sorry I can't reproduce your comment that the 2fa login would have ignored.i just release v0.27.3 you can try again
