### ISSUE TITLE
希望增加标签排序和修改日期功能 || I hope to add tag sorting and modification date functions

### ISSUE THREAD

**Issue by fantasyzyc** [blinko-space/blinko#344]
1. 标签目前排序规则希望能够自定义
2. 创建日期如果能在页面上直接改，而非数据库将方便很多

---
1. I hope the current sorting rules of labels can be customized.
2. It would be much more convenient if the creation date could be changed directly on the page instead of the database

**Comment by relines** [comment]
+1，希望增加修改闪念日期的功能

**Comment by blinko-space** [comment]
修改日期的功能已经有了

**Comment by jlhulclq** [comment]
标签拖拽排序，求！

> 修改日期的功能已经有了
> 
> The function of modifying date is already available

**Comment by blinko-space** [comment]
标签排序已经支持
