### ISSUE TITLE
'Embed Image' button is missing in the toolbar

### ISSUE THREAD

**Issue by bootnihil** [blinko-space/blinko#345]
**Describe the bug**
'Embed Image' button is missing in the toolbar.

Image from the docs:
![image](https://github.com/user-attachments/assets/c7cda3ed-59d0-4c72-95ff-3b7a21af7d6b)

Image from Docker deployment, app version 0.27.6:
![image](https://github.com/user-attachments/assets/883b0255-4082-4523-9c80-a63229cfca2c)

**Comment by bootnihil** [comment]
The toolbar in my deployment matches the one in the current demo instance, and both differ from the toolbar screenshot in the documentation and lack the 'embed image' button.

Screenshot from the demo instance:

![image](https://github.com/user-attachments/assets/9f64725d-5a00-4f6f-8b3d-7d8b1af4f8bb)

**Comment by blinko-space** [comment]
updated the documatiation https://blinko.mintlify.app/how-to-use/toolbar
