### ISSUE TITLE
移动端无法编辑时间 || Time cannot be edited on mobile terminal

### ISSUE THREAD

**Issue by relines** [blinko-space/blinko#348]
移动端编辑时间，确认按钮点击无反应，无法修改时间。

---
When editing the time on the mobile terminal, there is no response when clicking the confirmation button, and the time cannot be modified.

**Comment by Jonnyan404** [comment]
我也是这样，版本 0.27.6

**Comment by relines** [comment]
我也是0.27.6版本

**Comment by smallxi** [comment]
直接改时间没法保存，但是选择时间是可以保存的

**Comment by Jonnyan404** [comment]
v0.28.1 已修复
