### ISSUE TITLE
大佬后期会开发浏览器插件和app吗？以及能否支持其他的ai模型

### ISSUE THREAD

**Issue by ccdyd** [blinko-space/blinko#35]
浏览器插件真的非常方便，手机端的话方便记录，不用登录网页

**Comment by blinko-space** [comment]
1.目前项目还是初期阶段，在v.0.1.0版本上线了openapi的功能，开发者可以自己调用相关接口，后期应该会开发到
2.ai模型已经预留了相关接口后续也会支持
