### ISSUE TITLE
笔记分享使用加密或随机链接 || Use encrypted or random links for note sharing

### ISSUE THREAD

**Issue by BryceWG** [blinko-space/blinko#356]
**Is your feature request related to a problem? Please describe.**
笔记分享使用加密或随机链接,目前是域名/share/笔记ID的形式,域名被找到后可以直接遍历读取,隐私性较差

**Describe the solution you'd like**
笔记ID改成加密或随机链接,防止爆破

---
**Is your feature request related to a problem? Please describe.**
Note sharing uses encrypted or random links, currently in the form of domain name/share/note ID. Once the domain name is found, it can be directly traversed and read, and the privacy is poor.

**Describe the solution you'd like**
Change the note ID to an encrypted or random link to prevent explosions

**Comment by blinko-space** [comment]
supported on [v0.31.0](https://github.com/blinko-space/blinko/releases/tag/v0.31.0)
