### ISSUE TITLE
[功能请求] 希望在筛选项里增加一项笔记内链接的筛选。

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#36]
![PixPin_2024-11-10_13-47-59](https://github.com/user-attachments/assets/bbfd0947-726e-4bf1-a457-7f244d4f8b6d)

筛选笔记内的链接，感觉应该是也比较常用的功能之一。

- 比如记录了一条笔记，但是笔记内容只是摘要，完整的笔记内容来自某个网站。
- 快速在几百条笔记里筛选出少部分存在链接的笔记还是很方便的。

**Comment by blinko-space** [comment]
https://github.com/blinko-space/blinko/commit/9a5aac6adf49426c000476ef03f57bc86fa0e8d0
