### ISSUE TITLE
安卓输入法面板弹起后，保存等按钮都需要按 2 次 || After the Android input method panel pops up, the save and other buttons need to be pressed twice

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#361]
安卓输入法面板弹起后，保存等按钮都需要按 2 次

---
After the Android input method panel pops up, the save and other buttons need to be pressed twice

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the editor initialization and focus handling to address the Android input method panel issue. Added a new function to handle focus and scroll, and updated the editor initialization to use this function.

You can review changes in this commit: https://github.com/wwqwq2313/blinko-space-blinko-361/commit/fff486accba92cd942e0aae436cf59fd7d56c96b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Jonnyan404** [comment]
0.29.7 已修复
