### ISSUE TITLE
Role based sharing of notes with only internal users

### ISSUE THREAD

**Issue by himsin** [blinko-space/blinko#362]
I've multiple users configured and there are times when I would like to share a note with another user within same server.  I don't want this note to be public. 

1. Ability to share note with specific users
2. Ability to configure permissions on shared note e.g. read only, read+write.
3. Ability to add the shared note in notes section. If any of the user modifies the note then it will be reelected for all the users who have access to the note.

**Comment by blinko-space** [comment]
supported on [v0.31.0](https://github.com/blinko-space/blinko/releases/tag/v0.31.0)
No complicated rights management.Added passwords for protection
