### ISSUE TITLE
Request: Progressive web app or native mobile client

### ISSUE THREAD

**Issue by masoncfrancis** [blinko-space/blinko#365]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would love to see Blinko available as a Progressive Web App, or a native mobile client. I like to be able to manage my notes from my phone, but I would like to be able to add notes when I'm away from an internet connection, such as camping or hiking.

**Describe alternatives you've considered**
I could write an app that does this which would unfortunately be a huge undertaking for me. Another option is to write a connector to use a pre-existing open source mobile client to hook it up to the Blinko backend

**Comment by blinko-space** [comment]
at v0.30.4 version,we support offline mode that you can write your note without network and when you connect to network the note will be auto sync to the backend. But this is the simple support , you cannot do delete or update action
