### ISSUE TITLE
建议:分享短命令功能 || Suggestion: Share short command function

### ISSUE THREAD

**Issue by jiangxingxiao** [blinko-space/blinko#368]
首先谢谢作者的作品，今天部署使用，非常nice。
但有几点个人感觉可以优化的地方。
首先是分享功能，点选分享后，笔记的状态会直接变化成公开。感觉有几个方法，供作者参考。
1调整成短期口令的方式，类似网盘，可以允许未登录用户输入简单口令看到分享内容（参照云盘分享），这样就不用完全公开笔记内容了。

2:计时销毁，类似阅后即焚，分享有时限，或者查看次数，到时间或者次数，分享将重新回到个人私有取消公开状态。

3或者进行隐私分享时，添加自动登陆密钥，由管理员创建好用户，分享时自动为第一个打开的用户登陆查看半公开内容。（感觉这样操作复杂了，但不需要新的代码，是不是添加几个循环，指向可以实现。我是小白，说的蠢话的话还请作者见谅）

---
First of all, thank you to the author for his work. It is deployed and used today. It is very nice.
But there are a few things that I personally feel can be optimized.
The first is the sharing function. After clicking to share, the status of the note will directly change to public. I feel there are several methods for the author's reference.
1. Adjust to a short-term password method, similar to the cloud disk, which allows users who are not logged in to enter a simple password to see the shared content (refer to cloud disk sharing), so that the note content does not need to be fully disclosed.

2: Timed destruction, similar to burning after reading, sharing has a time limit, or the number of views. When the time or number of times is reached, the sharing will return to the personal private and unpublicized state.

3. Or when performing private sharing, add an automatic login key, and the administrator will create a user. When sharing, the first user to open the account will automatically log in to view the semi-public content. (I feel that this operation is complicated, but no new code is needed. Can I add a few loops and pointers to achieve it? I am a novice, so please forgive me if I say stupid things)

**Comment by blinko-space** [comment]
supported on [v0.31.0](https://github.com/blinko-space/blinko/releases/tag/v0.31.0)
