### ISSUE TITLE
对于折叠的长文内容无法实现双击编辑

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#37]
![image](https://github.com/user-attachments/assets/241f6e7c-c381-47a2-969d-c046d382b0e9)
比如这是一篇被折叠过的长文。
![image](https://github.com/user-attachments/assets/c860bbd5-e0cf-4a98-8811-bfb1702cfad7)
当要双击编辑这篇长文内容的时候，输入框内没有该篇笔记的信息。

**Comment by i-iooi-i** [comment]
似乎不是长文内容导致的无法编辑。
而是 笔记内 有 一级标题  二级标题  三级标题  都会导致无法双击编辑内容。

**Comment by blinko-space** [comment]
https://github.com/blinko-space/blinko/commit/724cfe117406a1b0e055d8d581e6831c00bc34c4
