### ISSUE TITLE
时间范围筛选不准 || Time range filtering is not allowed

### ISSUE THREAD

**Issue by relines** [blinko-space/blinko#376]
时间范围筛选不准，应该是没生效，而且移动端点击应用筛选按钮没反应，我使用的是0.30.3版本。

---
The time range filtering is not accurate, it should not be effective, and there is no response when clicking the application filter button on the mobile terminal. I am using version 0.30.3.

**Comment by blinko-space** [comment]
fixed in lastest version v0.30.5
