### ISSUE TITLE
几个小Bug || A few small bugs

### ISSUE THREAD

**Issue by qfqha** [blinko-space/blinko#387]
#几点小Bug
1. 使用目录下update.sh更新后，图片丢失了
![image](https://github.com/user-attachments/assets/58d7236b-b112-4e0b-a64f-57160049fe4e)
---
2. 即使在设置中禁止注册，任然可以直接访问/signup页面进行注册，默认user可以更改注册设置
---
3. 在部署到Vercel的时候无法注册，登录提示服务器错误（注册页、登录页均可以访问，使用Neon的postgres数据库）
![image](https://github.com/user-attachments/assets/2176c7df-f9fb-4977-acb5-5fd4dd9eaf30)

---
#a few small bugs
1. After updating using update.sh in the directory, the picture is lost.
![image](https://github.com/user-attachments/assets/58d7236b-b112-4e0b-a64f-57160049fe4e)
---
2. Even if registration is prohibited in the settings, you can still directly access the /signup page to register. The default user can change the registration settings.
---
3. Unable to register when deploying to Vercel, and a server error is prompted when logging in (both the registration page and login page can be accessed, using Neon's postgres database)
![image](https://github.com/user-attachments/assets/2176c7df-f9fb-4977-acb5-5fd4dd9eaf30)

**Comment by blinko-space** [comment]
登录权限已经修复。vercel的错误是由于vercel内部无法访问文件系统，目前不推荐部署到vercel

**Comment by blinko-space** [comment]
update.sh没有进行其他的额外操作 如果是用docker进行部署一定要记得挂载目录到.blinko文件夹 使用update.sh会在sh运行目录下生成备份文件 解压blinko容器内部关联的.blinko文件夹内即可
