### ISSUE TITLE
Vercel部署报错了

### ISSUE THREAD

**Issue by leslieyin** [blinko-space/blinko#39]
![微信截图_20241110172335](https://github.com/user-attachments/assets/7036c664-2a05-4998-b5c7-e28eb2bc7771)
看见大佬的demo地址是vercel的，我也尝试用vercel部署了下，报错了。菜鸟不知道啥问题，大佬有空帮忙看看♥

**Comment by blinko-space** [comment]
拉取最新代码即可 正好刚才推了一些代码

**Comment by leslieyin** [comment]
> 拉取最新代码即可 正好刚才推了一些代码
好的，我再试试，谢谢大佬！
