### ISSUE TITLE
Markdown图片链接无法被二次编辑

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#40]
插入在笔记中的Markdown图片无法被二次编辑了，或者说双击编辑的时候，这段Markdown信息不可见了。辛苦大佬看看。
https://github.com/user-attachments/assets/e9360786-63dd-4756-893c-45a6af78c683
Markdown 图片如下：
`[![pA6HdRe.png](https://s21.ax1x.com/2024/11/10/pA6HdRe.png)](https://imgse.com/i/pA6HdRe)`

**Comment by blinko-space** [comment]
这个也是在新版被修复的

**Comment by i-iooi-i** [comment]
> 这个也是在新版被修复的

很棒啦辛苦大佬，暂时找不到什么问题啦。🌹
