### ISSUE TITLE
移动端体验问题

### ISSUE THREAD

**Issue by leslieyin** [blinko-space/blinko#44]
设备：iphone13pm
方式：添加到主屏幕pwa模式

问题：
1.点击侧栏时，菜单弹出和收回显卡顿
2.点击底部输入框输入内容时，偶尔出现键盘无法输入的情况，关闭页面后台 重新进入后恢复，非必现问题

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blinko-space** [comment]
最新版已经修复
