### ISSUE TITLE
关于AI的错误问题

### ISSUE THREAD

**Issue by i-iooi-i** [blinko-space/blinko#48]
![image](https://github.com/user-attachments/assets/10aa5990-e0c3-4fe7-a025-44ce7fa928d0)

当使用AI查询笔记内容的时候，它明明已经检索出了一条笔记信息的，但是它的回答还是：对不起，我无法从提供的信息中找到关于“AWS”的笔记。

![image](https://github.com/user-attachments/assets/28b46964-c5cb-4aa4-a0d9-05f55f47d56e)
此时点开这条笔记，并双击这条笔记。

![image](https://github.com/user-attachments/assets/0bdbab3c-da16-477e-b43d-377e85b7896e)
就会出现报错页面了。

大概问题就是这么复现的，还请大佬抽空看看。

**Comment by blinko-space** [comment]
这个笔记内容似乎没有aws的内容 是搜错了吗

**Comment by yinan-c** [comment]
也有类似的问题，AI 总是回答 我不知道，我不清楚，却在下面推荐了正确的内容。

**Comment by violin321** [comment]
好像也有另一个问题，使用AI查询笔记内容的时候，检索推荐出多条闪念/笔记信息。但是当点击跳转了第一次点击的链接后，无法点击另外一个链接进行跳转。点击后，上方有加载条但是只会留在第一次跳转的页面并不会跳转到新链接。
<img width="613" alt="image" src="https://github.com/user-attachments/assets/8d8de95c-ddc3-4129-96a8-5cbf24b9e62a">

**Comment by blinko-space** [comment]
this bug already fixed
