### ISSUE TITLE
Login problems deployed to vercel

### ISSUE THREAD

**Issue by yordyi** [blinko-space/blinko#50]
# 我遇到一个问题,我尝试fork源仓库到我的github账号之中,并尝试部署到vercel,但是我无法注册,也无法登录,我只能在本机电脑上使用docker才可以使用.
<img width="604" alt="image" src="https://github.com/user-attachments/assets/dec2038e-0b06-4a95-a725-0565fadf7f87">

**Comment by blinko-space** [comment]
请在vercel build命令使用vercel-build未来会有vercel部署教程
