### ISSUE TITLE
建议：长文本的编辑状态在顶部和底部增加留白

### ISSUE THREAD

**Issue by gituser056391** [blinko-space/blinko#58]
长文本在编辑状态时，建议在顶部和底部增加留白，这样看起来会更加美观，移动端则尽量取消留白

![image](https://github.com/user-attachments/assets/2dc6b4a7-bda6-4c90-a176-21d6f1e20128)

**Comment by blinko-space** [comment]
fixed on https://github.com/blinko-space/blinko/releases/tag/v0.3.4
