### ISSUE TITLE
建议：增大工具栏按钮的水平间距

### ISSUE THREAD

**Issue by gituser056391** [blinko-space/blinko#63]
在移动端，工具栏的按钮太小，过于拥挤，建议取消下图位置的空白，增大按钮间距，做到自适应分布，同时按照这个思路优化大屏时的按钮间距

![image](https://github.com/user-attachments/assets/5e730681-c9ec-4d14-bb61-8f32e1ae8931)

**Comment by blinko-space** [comment]
v0.11.0已经优化了移动端显示
