### ISSUE TITLE
建议：移动端页面在按 Back 键（安卓）时采用更精准的返回层级策略

### ISSUE THREAD

**Issue by gituser056391** [blinko-space/blinko#66]
比如编辑文字保存之前按 Back 键，预期的表现是退出编辑，但目前的实际表现是浏览器返回到上一个加载的网址，建议按照移动 APP 的返回策略优化 Back 键的表现

**Comment by blinko-space** [comment]
弹框的一些逻辑已经优化 例如移动端返回 关闭弹框
