### ISSUE TITLE
建议：移动端新建内容时，文本框之外的区域以模糊方式显示

### ISSUE THREAD

**Issue by gituser056391** [blinko-space/blinko#70]
新建内容时采用与编辑旧内容时相同的模糊效果，这样可以降低界面凌乱程度，让注意力更加聚焦到新建内容上面。

注：如果用户需要在对比旧内容的同时新建内容，那么把这个特性作为一个可选项。

![IMG_20241112_222809.jpg](https://github.com/user-attachments/assets/c4341fa5-34cf-4ca6-8ab2-024e5906c716)

**Comment by blinko-space** [comment]
最新版已增加
