### ISSUE TITLE
建议：移动端编辑旧内容时的文本框对齐方式改为自适应垂直居中显示

### ISSUE THREAD

**Issue by gituser056391** [blinko-space/blinko#71]
目前的靠底部对齐感觉有点奇怪，看起来不太协调，建议改为在垂直方向自适应居中显示，与桌面端的对齐方式保持一致。如果居中的小细条看着不舒服，可以将文本框的默认最小高度增大一点。

![IMG_20241112_223752.jpg](https://github.com/user-attachments/assets/6d01aa67-c98c-4f41-872b-221bc737a6f8)

**Comment by blinko-space** [comment]
放在下面是考虑到移动端方便点击弹出输入法
