### ISSUE TITLE
Support more AI providers and AI models

### ISSUE THREAD

**Issue by DHS1001** [blinko-space/blinko#74]
Thanks for the project.
The current version only support OpenAI as the AP provider and limited number of AI models.
It would be great if other AI providers and more models can be supported, for example: Ollama, LM studio, etc.

**Comment by SupportSpark** [comment]
在增加对第三方中转接口支持如new-api等，并且支持自定义模型，

**Comment by DHS1001** [comment]
Thanks @blinko-space.
Ollama is supported in the latest 0.11.0
