### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by firestrife23** [blinko-space/blinko#76]
I enjoy it, but for some reason it didn't function with Traefik, which manages SSL termination. I also tried setting the environment for the public-facing URL, and it's still not working for me.

**Comment by tzwaeaen** [comment]
For me the healthcheck was not working. I removed it from the docker compose and now it is working with traefik. 🤷

**Comment by blinko-space** [comment]
this might not be an issue with Blinko. I would suggest checking your Traefik configuration to ensure there are no routing or SSL termination issues. Make sure Traefik is correctly handling the HTTPS requests and that the relevant environment variables are set properly."

**Comment by victornavorskie** [comment]
Same problem here, with NEXTAUTH_URL showing Bad Gateway.

**Comment by jermanoid** [comment]
That worked for me. I was on that path initially and tried ordering them in compose which didn't change the subnet listed in the blinko logs at runtime. Glad I stumbled on this

**Comment by ChickenSaysBak** [comment]
I also experienced this using Caddy.

Setting blink's network name to "z-blinko-network" did the trick. Thanks!

**Comment by akrauss** [comment]
Why closed, this is a Bug!

**Comment by themadcodger** [comment]
Yeah, this shouldn't be closed. I also had to change the network name to `z-blinko-network` in order to get it to work with my reverse proxy, which I wouldn't have figured out if not for the poster above.
