### ISSUE TITLE
主页内容列表的菜单按钮，上下抖动，无法精准点击

### ISSUE THREAD

**Issue by Jonnyan404** [blinko-space/blinko#88]
尤其在移动端，会导致菜单选项无法弹出，要重复点击多次

**Comment by blinko-space** [comment]
可以详细描述一下吗

**Comment by Jonnyan404** [comment]
> 可以详细描述一下吗


https://github.com/user-attachments/assets/20819c68-a2e3-4113-bb05-9b071aa2feb4

我录了一下视频，你看看的

**Comment by blinko-space** [comment]
fix on v0.3.4
